#import <Foundation/Foundation.h>
#import <AFNetworking/AFURLRequestSerialization.h>

/**
* Skycoin REST API.
* Skycoin is a next-generation cryptocurrency.
*
* OpenAPI spec version: 0.25.1
* Contact: contact@skycoin.net
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


@interface OAIJSONRequestSerializer : AFJSONRequestSerializer
@end
