#import <Foundation/Foundation.h>
#import <CoreData/CoreData.h>

#import "OAIApiv1exploreraddressOutputsManagedObjectBuilder.h"

#import "OAIApiv1pendingTxsTransactionManagedObject.h"
#import "OAIApiv1pendingTxsTransaction.h"

/**
* Skycoin REST API.
* Skycoin is a next-generation cryptocurrency.
*
* OpenAPI spec version: 0.25.1
* Contact: contact@skycoin.net
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


@interface OAIApiv1pendingTxsTransactionManagedObjectBuilder : NSObject

@property (nonatomic, strong) OAIApiv1exploreraddressOutputsManagedObjectBuilder * outputsBuilder;


-(OAIApiv1pendingTxsTransactionManagedObject*)createNewOAIApiv1pendingTxsTransactionManagedObjectInContext:(NSManagedObjectContext*)context;

-(OAIApiv1pendingTxsTransactionManagedObject*)OAIApiv1pendingTxsTransactionManagedObjectFromOAIApiv1pendingTxsTransaction:(OAIApiv1pendingTxsTransaction*)object context:(NSManagedObjectContext*)context;

-(void)updateOAIApiv1pendingTxsTransactionManagedObject:(OAIApiv1pendingTxsTransactionManagedObject*)object withOAIApiv1pendingTxsTransaction:(OAIApiv1pendingTxsTransaction*)object2;

-(OAIApiv1pendingTxsTransaction*)OAIApiv1pendingTxsTransactionFromOAIApiv1pendingTxsTransactionManagedObject:(OAIApiv1pendingTxsTransactionManagedObject*)obj;

-(void)updateOAIApiv1pendingTxsTransaction:(OAIApiv1pendingTxsTransaction*)object withOAIApiv1pendingTxsTransactionManagedObject:(OAIApiv1pendingTxsTransactionManagedObject*)object2;

@end
