#import <Foundation/Foundation.h>
#import <CoreData/CoreData.h>

/**
* Skycoin REST API.
* Skycoin is a next-generation cryptocurrency.
*
* OpenAPI spec version: 0.25.1
* Contact: contact@skycoin.net
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "OAIApiv1exploreraddressOutputsManagedObject.h"


NS_ASSUME_NONNULL_BEGIN

@interface OAIApiv1pendingTxsTransactionManagedObject : NSManagedObject


@property (nullable, nonatomic, retain) NSOrderedSet<OAIApiv1exploreraddressOutputsManagedObject*>* outputs;

@property (nullable, nonatomic, retain) NSString* innerHash;

@property (nullable, nonatomic, retain) NSArray<NSString*>* inputs;

@property (nullable, nonatomic, retain) NSArray<NSString*>* sigs;

@property (nullable, nonatomic, retain) NSNumber* length;

@property (nullable, nonatomic, retain) NSString* txid;

@property (nullable, nonatomic, retain) NSNumber* type;

@property (nullable, nonatomic, retain) NSNumber* timestamp;
@end

@interface OAIApiv1pendingTxsTransactionManagedObject (GeneratedAccessors)
- (void)addOutputsObject:(OAIApiv1exploreraddressOutputsManagedObject *)value;
- (void)removeOutputsObject:(OAIApiv1exploreraddressOutputsManagedObject *)value;
- (void)addOutputs:(NSOrderedSet<OAIApiv1exploreraddressOutputsManagedObject*> *)values;
- (void)removeOutputs:(NSOrderedSet<OAIApiv1exploreraddressOutputsManagedObject*> *)values;

@end


NS_ASSUME_NONNULL_END
