

#import "OAIApiv1walletsEntriesManagedObjectBuilder.h"

/**
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

@implementation OAIApiv1walletsEntriesManagedObjectBuilder

-(instancetype)init {
    self = [super init];
    if (self != nil) {
    }
    return self;
}

-(OAIApiv1walletsEntriesManagedObject*)createNewOAIApiv1walletsEntriesManagedObjectInContext:(NSManagedObjectContext*)context {
    OAIApiv1walletsEntriesManagedObject *managedObject = [NSEntityDescription insertNewObjectForEntityForName:NSStringFromClass([OAIApiv1walletsEntriesManagedObject class]) inManagedObjectContext:context];
    return managedObject;
}

-(OAIApiv1walletsEntriesManagedObject*)OAIApiv1walletsEntriesManagedObjectFromOAIApiv1walletsEntries:(OAIApiv1walletsEntries*)object context:(NSManagedObjectContext*)context {
    OAIApiv1walletsEntriesManagedObject* newOAIApiv1walletsEntries = [self createNewOAIApiv1walletsEntriesManagedObjectInContext:context];
    [self updateOAIApiv1walletsEntriesManagedObject:newOAIApiv1walletsEntries withOAIApiv1walletsEntries:object];
    return newOAIApiv1walletsEntries;
}

-(void)updateOAIApiv1walletsEntriesManagedObject:(OAIApiv1walletsEntriesManagedObject*)managedObject withOAIApiv1walletsEntries:(OAIApiv1walletsEntries*)object {
    if(!managedObject || !object) {
        return;
    }
    NSManagedObjectContext* context = managedObject.managedObjectContext;
    managedObject.publicKey = [object.publicKey copy];
    managedObject.address = [object.address copy];

}

-(OAIApiv1walletsEntries*)OAIApiv1walletsEntriesFromOAIApiv1walletsEntriesManagedObject:(OAIApiv1walletsEntriesManagedObject*)obj {
    if(!obj) {
        return nil;
    }
    OAIApiv1walletsEntries* newOAIApiv1walletsEntries = [[OAIApiv1walletsEntries alloc] init];
    [self updateOAIApiv1walletsEntries:newOAIApiv1walletsEntries withOAIApiv1walletsEntriesManagedObject:obj];
    return newOAIApiv1walletsEntries;
}

-(void)updateOAIApiv1walletsEntries:(OAIApiv1walletsEntries*)newOAIApiv1walletsEntries withOAIApiv1walletsEntriesManagedObject:(OAIApiv1walletsEntriesManagedObject*)obj {
    newOAIApiv1walletsEntries.publicKey = [obj.publicKey copy];
    newOAIApiv1walletsEntries.address = [obj.address copy];
}

@end
