#import "OAIApiv1pendingTxsTransactionManagedObject.h"

/**
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
@implementation OAIApiv1pendingTxsTransactionManagedObject

@dynamic outputs;
@dynamic innerHash;
@dynamic inputs;
@dynamic sigs;
@dynamic length;
@dynamic txid;
@dynamic type;
@dynamic timestamp;
@end
