#import "OAIApiv1exploreraddressOutputsManagedObject.h"

/**
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
@implementation OAIApiv1exploreraddressOutputsManagedObject

@dynamic hours;
@dynamic dst;
@dynamic coins;
@dynamic uxid;
@end
