#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Skycoin REST API.
* Skycoin is a next-generation cryptocurrency.
*
* OpenAPI spec version: 0.25.1
* Contact: skycoin.doe@example.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol OAIApiv1walletsMeta
@end

@interface OAIApiv1walletsMeta : OAIObject


@property(nonatomic) NSString* filename;

@property(nonatomic) NSNumber* encrypted;

@property(nonatomic) NSString* cryptoType;

@property(nonatomic) NSString* label;

@property(nonatomic) NSString* type;

@property(nonatomic) NSString* version;

@property(nonatomic) NSString* coin;

@property(nonatomic) NSNumber* timestamp;

@end
