#import <Foundation/Foundation.h>
#import <CoreData/CoreData.h>


#import "OAIApiv1exploreraddressStatusManagedObject.h"
#import "OAIApiv1exploreraddressStatus.h"

/**
* Skycoin REST API.
* Skycoin is a next-generation cryptocurrency.
*
* OpenAPI spec version: 0.25.1
* Contact: contact@skycoin.net
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


@interface OAIApiv1exploreraddressStatusManagedObjectBuilder : NSObject



-(OAIApiv1exploreraddressStatusManagedObject*)createNewOAIApiv1exploreraddressStatusManagedObjectInContext:(NSManagedObjectContext*)context;

-(OAIApiv1exploreraddressStatusManagedObject*)OAIApiv1exploreraddressStatusManagedObjectFromOAIApiv1exploreraddressStatus:(OAIApiv1exploreraddressStatus*)object context:(NSManagedObjectContext*)context;

-(void)updateOAIApiv1exploreraddressStatusManagedObject:(OAIApiv1exploreraddressStatusManagedObject*)object withOAIApiv1exploreraddressStatus:(OAIApiv1exploreraddressStatus*)object2;

-(OAIApiv1exploreraddressStatus*)OAIApiv1exploreraddressStatusFromOAIApiv1exploreraddressStatusManagedObject:(OAIApiv1exploreraddressStatusManagedObject*)obj;

-(void)updateOAIApiv1exploreraddressStatus:(OAIApiv1exploreraddressStatus*)object withOAIApiv1exploreraddressStatusManagedObject:(OAIApiv1exploreraddressStatusManagedObject*)object2;

@end
