#import "OAIApiv1walletsMetaManagedObject.h"

/**
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
@implementation OAIApiv1walletsMetaManagedObject

@dynamic filename;
@dynamic encrypted;
@dynamic cryptoType;
@dynamic label;
@dynamic type;
@dynamic version;
@dynamic coin;
@dynamic timestamp;
@end
