#import "OAIApiv1exploreraddressInputsManagedObject.h"

/**
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
@implementation OAIApiv1exploreraddressInputsManagedObject

@dynamic owner;
@dynamic hours;
@dynamic calculatedHours;
@dynamic coins;
@dynamic uxid;
@end
