

#import "OAIApiv1wallettransactionToManagedObjectBuilder.h"

/**
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

@implementation OAIApiv1wallettransactionToManagedObjectBuilder

-(instancetype)init {
    self = [super init];
    if (self != nil) {
    }
    return self;
}

-(OAIApiv1wallettransactionToManagedObject*)createNewOAIApiv1wallettransactionToManagedObjectInContext:(NSManagedObjectContext*)context {
    OAIApiv1wallettransactionToManagedObject *managedObject = [NSEntityDescription insertNewObjectForEntityForName:NSStringFromClass([OAIApiv1wallettransactionToManagedObject class]) inManagedObjectContext:context];
    return managedObject;
}

-(OAIApiv1wallettransactionToManagedObject*)OAIApiv1wallettransactionToManagedObjectFromOAIApiv1wallettransactionTo:(OAIApiv1wallettransactionTo*)object context:(NSManagedObjectContext*)context {
    OAIApiv1wallettransactionToManagedObject* newOAIApiv1wallettransactionTo = [self createNewOAIApiv1wallettransactionToManagedObjectInContext:context];
    [self updateOAIApiv1wallettransactionToManagedObject:newOAIApiv1wallettransactionTo withOAIApiv1wallettransactionTo:object];
    return newOAIApiv1wallettransactionTo;
}

-(void)updateOAIApiv1wallettransactionToManagedObject:(OAIApiv1wallettransactionToManagedObject*)managedObject withOAIApiv1wallettransactionTo:(OAIApiv1wallettransactionTo*)object {
    if(!managedObject || !object) {
        return;
    }
    NSManagedObjectContext* context = managedObject.managedObjectContext;
    managedObject.hours = [object.hours copy];
    managedObject.address = [object.address copy];
    managedObject.coins = [object.coins copy];

}

-(OAIApiv1wallettransactionTo*)OAIApiv1wallettransactionToFromOAIApiv1wallettransactionToManagedObject:(OAIApiv1wallettransactionToManagedObject*)obj {
    if(!obj) {
        return nil;
    }
    OAIApiv1wallettransactionTo* newOAIApiv1wallettransactionTo = [[OAIApiv1wallettransactionTo alloc] init];
    [self updateOAIApiv1wallettransactionTo:newOAIApiv1wallettransactionTo withOAIApiv1wallettransactionToManagedObject:obj];
    return newOAIApiv1wallettransactionTo;
}

-(void)updateOAIApiv1wallettransactionTo:(OAIApiv1wallettransactionTo*)newOAIApiv1wallettransactionTo withOAIApiv1wallettransactionToManagedObject:(OAIApiv1wallettransactionToManagedObject*)obj {
    newOAIApiv1wallettransactionTo.hours = [obj.hours copy];
    newOAIApiv1wallettransactionTo.address = [obj.address copy];
    newOAIApiv1wallettransactionTo.coins = [obj.coins copy];
}

@end
