#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Skycoin REST API.
* Skycoin is a next-generation cryptocurrency.
*
* OpenAPI spec version: 0.25.1
* Contact: contact@skycoin.net
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol OAIApiv1wallettransactionHoursSelection
@end

@interface OAIApiv1wallettransactionHoursSelection : OAIObject


@property(nonatomic) NSString* mode;

@property(nonatomic) NSString* shareFactor;

@property(nonatomic) NSString* type;

@end
