#import <Foundation/Foundation.h>
#import <CoreData/CoreData.h>

/**
* Skycoin REST API.
* Skycoin is a next-generation cryptocurrency.
*
* OpenAPI spec version: 0.25.1
* Contact: contact@skycoin.net
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/




NS_ASSUME_NONNULL_BEGIN

@interface OAIApiv1exploreraddressStatusManagedObject : NSManagedObject


@property (nullable, nonatomic, retain) NSNumber* unconfirmed;

@property (nullable, nonatomic, retain) NSNumber* blockSeq;

@property (nullable, nonatomic, retain) NSNumber* label;

@property (nullable, nonatomic, retain) NSNumber* confirmed;
@end

@interface OAIApiv1exploreraddressStatusManagedObject (GeneratedAccessors)

@end


NS_ASSUME_NONNULL_END
