#import "OAIApiv1wallettransactionHoursSelectionManagedObject.h"

/**
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
@implementation OAIApiv1wallettransactionHoursSelectionManagedObject

@dynamic mode;
@dynamic shareFactor;
@dynamic type;
@end
