#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Skycoin REST API.
* Skycoin is a next-generation cryptocurrency.
*
* OpenAPI spec version: 0.25.1
* Contact: skycoin.doe@example.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol OAIApiv1exploreraddressInputs
@end

@interface OAIApiv1exploreraddressInputs : OAIObject


@property(nonatomic) NSString* owner;

@property(nonatomic) NSNumber* hours;

@property(nonatomic) NSNumber* calculatedHours;

@property(nonatomic) NSString* coins;

@property(nonatomic) NSString* uxid;

@end
