

#import "OAIApiv1wallettransactionHoursSelectionManagedObjectBuilder.h"

/**
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

@implementation OAIApiv1wallettransactionHoursSelectionManagedObjectBuilder

-(instancetype)init {
    self = [super init];
    if (self != nil) {
    }
    return self;
}

-(OAIApiv1wallettransactionHoursSelectionManagedObject*)createNewOAIApiv1wallettransactionHoursSelectionManagedObjectInContext:(NSManagedObjectContext*)context {
    OAIApiv1wallettransactionHoursSelectionManagedObject *managedObject = [NSEntityDescription insertNewObjectForEntityForName:NSStringFromClass([OAIApiv1wallettransactionHoursSelectionManagedObject class]) inManagedObjectContext:context];
    return managedObject;
}

-(OAIApiv1wallettransactionHoursSelectionManagedObject*)OAIApiv1wallettransactionHoursSelectionManagedObjectFromOAIApiv1wallettransactionHoursSelection:(OAIApiv1wallettransactionHoursSelection*)object context:(NSManagedObjectContext*)context {
    OAIApiv1wallettransactionHoursSelectionManagedObject* newOAIApiv1wallettransactionHoursSelection = [self createNewOAIApiv1wallettransactionHoursSelectionManagedObjectInContext:context];
    [self updateOAIApiv1wallettransactionHoursSelectionManagedObject:newOAIApiv1wallettransactionHoursSelection withOAIApiv1wallettransactionHoursSelection:object];
    return newOAIApiv1wallettransactionHoursSelection;
}

-(void)updateOAIApiv1wallettransactionHoursSelectionManagedObject:(OAIApiv1wallettransactionHoursSelectionManagedObject*)managedObject withOAIApiv1wallettransactionHoursSelection:(OAIApiv1wallettransactionHoursSelection*)object {
    if(!managedObject || !object) {
        return;
    }
    NSManagedObjectContext* context = managedObject.managedObjectContext;
    managedObject.mode = [object.mode copy];
    managedObject.shareFactor = [object.shareFactor copy];
    managedObject.type = [object.type copy];

}

-(OAIApiv1wallettransactionHoursSelection*)OAIApiv1wallettransactionHoursSelectionFromOAIApiv1wallettransactionHoursSelectionManagedObject:(OAIApiv1wallettransactionHoursSelectionManagedObject*)obj {
    if(!obj) {
        return nil;
    }
    OAIApiv1wallettransactionHoursSelection* newOAIApiv1wallettransactionHoursSelection = [[OAIApiv1wallettransactionHoursSelection alloc] init];
    [self updateOAIApiv1wallettransactionHoursSelection:newOAIApiv1wallettransactionHoursSelection withOAIApiv1wallettransactionHoursSelectionManagedObject:obj];
    return newOAIApiv1wallettransactionHoursSelection;
}

-(void)updateOAIApiv1wallettransactionHoursSelection:(OAIApiv1wallettransactionHoursSelection*)newOAIApiv1wallettransactionHoursSelection withOAIApiv1wallettransactionHoursSelectionManagedObject:(OAIApiv1wallettransactionHoursSelectionManagedObject*)obj {
    newOAIApiv1wallettransactionHoursSelection.mode = [obj.mode copy];
    newOAIApiv1wallettransactionHoursSelection.shareFactor = [obj.shareFactor copy];
    newOAIApiv1wallettransactionHoursSelection.type = [obj.type copy];
}

@end
