#import "OAIApiv1walletsEntriesManagedObject.h"

/**
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
@implementation OAIApiv1walletsEntriesManagedObject

@dynamic publicKey;
@dynamic address;
@end
