#import <Foundation/Foundation.h>
#import <CoreData/CoreData.h>


#import "OAIApiv1exploreraddressOutputsManagedObject.h"
#import "OAIApiv1exploreraddressOutputs.h"

/**
* Skycoin REST API.
* Skycoin is a next-generation cryptocurrency.
*
* OpenAPI spec version: 0.25.1
* Contact: contact@skycoin.net
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


@interface OAIApiv1exploreraddressOutputsManagedObjectBuilder : NSObject



-(OAIApiv1exploreraddressOutputsManagedObject*)createNewOAIApiv1exploreraddressOutputsManagedObjectInContext:(NSManagedObjectContext*)context;

-(OAIApiv1exploreraddressOutputsManagedObject*)OAIApiv1exploreraddressOutputsManagedObjectFromOAIApiv1exploreraddressOutputs:(OAIApiv1exploreraddressOutputs*)object context:(NSManagedObjectContext*)context;

-(void)updateOAIApiv1exploreraddressOutputsManagedObject:(OAIApiv1exploreraddressOutputsManagedObject*)object withOAIApiv1exploreraddressOutputs:(OAIApiv1exploreraddressOutputs*)object2;

-(OAIApiv1exploreraddressOutputs*)OAIApiv1exploreraddressOutputsFromOAIApiv1exploreraddressOutputsManagedObject:(OAIApiv1exploreraddressOutputsManagedObject*)obj;

-(void)updateOAIApiv1exploreraddressOutputs:(OAIApiv1exploreraddressOutputs*)object withOAIApiv1exploreraddressOutputsManagedObject:(OAIApiv1exploreraddressOutputsManagedObject*)object2;

@end
