

#import "OAIApiv1exploreraddressInputsManagedObjectBuilder.h"

/**
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

@implementation OAIApiv1exploreraddressInputsManagedObjectBuilder

-(instancetype)init {
    self = [super init];
    if (self != nil) {
    }
    return self;
}

-(OAIApiv1exploreraddressInputsManagedObject*)createNewOAIApiv1exploreraddressInputsManagedObjectInContext:(NSManagedObjectContext*)context {
    OAIApiv1exploreraddressInputsManagedObject *managedObject = [NSEntityDescription insertNewObjectForEntityForName:NSStringFromClass([OAIApiv1exploreraddressInputsManagedObject class]) inManagedObjectContext:context];
    return managedObject;
}

-(OAIApiv1exploreraddressInputsManagedObject*)OAIApiv1exploreraddressInputsManagedObjectFromOAIApiv1exploreraddressInputs:(OAIApiv1exploreraddressInputs*)object context:(NSManagedObjectContext*)context {
    OAIApiv1exploreraddressInputsManagedObject* newOAIApiv1exploreraddressInputs = [self createNewOAIApiv1exploreraddressInputsManagedObjectInContext:context];
    [self updateOAIApiv1exploreraddressInputsManagedObject:newOAIApiv1exploreraddressInputs withOAIApiv1exploreraddressInputs:object];
    return newOAIApiv1exploreraddressInputs;
}

-(void)updateOAIApiv1exploreraddressInputsManagedObject:(OAIApiv1exploreraddressInputsManagedObject*)managedObject withOAIApiv1exploreraddressInputs:(OAIApiv1exploreraddressInputs*)object {
    if(!managedObject || !object) {
        return;
    }
    NSManagedObjectContext* context = managedObject.managedObjectContext;
    managedObject.owner = [object.owner copy];
    managedObject.hours = [object.hours copy];
    managedObject.calculatedHours = [object.calculatedHours copy];
    managedObject.coins = [object.coins copy];
    managedObject.uxid = [object.uxid copy];

}

-(OAIApiv1exploreraddressInputs*)OAIApiv1exploreraddressInputsFromOAIApiv1exploreraddressInputsManagedObject:(OAIApiv1exploreraddressInputsManagedObject*)obj {
    if(!obj) {
        return nil;
    }
    OAIApiv1exploreraddressInputs* newOAIApiv1exploreraddressInputs = [[OAIApiv1exploreraddressInputs alloc] init];
    [self updateOAIApiv1exploreraddressInputs:newOAIApiv1exploreraddressInputs withOAIApiv1exploreraddressInputsManagedObject:obj];
    return newOAIApiv1exploreraddressInputs;
}

-(void)updateOAIApiv1exploreraddressInputs:(OAIApiv1exploreraddressInputs*)newOAIApiv1exploreraddressInputs withOAIApiv1exploreraddressInputsManagedObject:(OAIApiv1exploreraddressInputsManagedObject*)obj {
    newOAIApiv1exploreraddressInputs.owner = [obj.owner copy];
    newOAIApiv1exploreraddressInputs.hours = [obj.hours copy];
    newOAIApiv1exploreraddressInputs.calculatedHours = [obj.calculatedHours copy];
    newOAIApiv1exploreraddressInputs.coins = [obj.coins copy];
    newOAIApiv1exploreraddressInputs.uxid = [obj.uxid copy];
}

@end
