#import "OAIApiv1exploreraddressStatusManagedObject.h"

/**
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
@implementation OAIApiv1exploreraddressStatusManagedObject

@dynamic unconfirmed;
@dynamic blockSeq;
@dynamic label;
@dynamic confirmed;
@end
