#import <Foundation/Foundation.h>
#import <CoreData/CoreData.h>


#import "OAIApiv1exploreraddressInputsManagedObject.h"
#import "OAIApiv1exploreraddressInputs.h"

/**
* Skycoin REST API.
* Skycoin is a next-generation cryptocurrency.
*
* OpenAPI spec version: 0.25.1
* Contact: contact@skycoin.net
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


@interface OAIApiv1exploreraddressInputsManagedObjectBuilder : NSObject



-(OAIApiv1exploreraddressInputsManagedObject*)createNewOAIApiv1exploreraddressInputsManagedObjectInContext:(NSManagedObjectContext*)context;

-(OAIApiv1exploreraddressInputsManagedObject*)OAIApiv1exploreraddressInputsManagedObjectFromOAIApiv1exploreraddressInputs:(OAIApiv1exploreraddressInputs*)object context:(NSManagedObjectContext*)context;

-(void)updateOAIApiv1exploreraddressInputsManagedObject:(OAIApiv1exploreraddressInputsManagedObject*)object withOAIApiv1exploreraddressInputs:(OAIApiv1exploreraddressInputs*)object2;

-(OAIApiv1exploreraddressInputs*)OAIApiv1exploreraddressInputsFromOAIApiv1exploreraddressInputsManagedObject:(OAIApiv1exploreraddressInputsManagedObject*)obj;

-(void)updateOAIApiv1exploreraddressInputs:(OAIApiv1exploreraddressInputs*)object withOAIApiv1exploreraddressInputsManagedObject:(OAIApiv1exploreraddressInputsManagedObject*)object2;

@end
