#import <Foundation/Foundation.h>
#import <CoreData/CoreData.h>


#import "OAIApiv1walletsMetaManagedObject.h"
#import "OAIApiv1walletsMeta.h"

/**
* Skycoin REST API.
* Skycoin is a next-generation cryptocurrency.
*
* OpenAPI spec version: 0.25.1
* Contact: contact@skycoin.net
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


@interface OAIApiv1walletsMetaManagedObjectBuilder : NSObject



-(OAIApiv1walletsMetaManagedObject*)createNewOAIApiv1walletsMetaManagedObjectInContext:(NSManagedObjectContext*)context;

-(OAIApiv1walletsMetaManagedObject*)OAIApiv1walletsMetaManagedObjectFromOAIApiv1walletsMeta:(OAIApiv1walletsMeta*)object context:(NSManagedObjectContext*)context;

-(void)updateOAIApiv1walletsMetaManagedObject:(OAIApiv1walletsMetaManagedObject*)object withOAIApiv1walletsMeta:(OAIApiv1walletsMeta*)object2;

-(OAIApiv1walletsMeta*)OAIApiv1walletsMetaFromOAIApiv1walletsMetaManagedObject:(OAIApiv1walletsMetaManagedObject*)obj;

-(void)updateOAIApiv1walletsMeta:(OAIApiv1walletsMeta*)object withOAIApiv1walletsMetaManagedObject:(OAIApiv1walletsMetaManagedObject*)object2;

@end
