#import "OAIApiv1wallettransactionToManagedObject.h"

/**
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
@implementation OAIApiv1wallettransactionToManagedObject

@dynamic hours;
@dynamic address;
@dynamic coins;
@end
