#import <Foundation/Foundation.h>
#import <CoreData/CoreData.h>


#import "OAIApiv1walletsEntriesManagedObject.h"
#import "OAIApiv1walletsEntries.h"

/**
* Skycoin REST API.
* Skycoin is a next-generation cryptocurrency.
*
* OpenAPI spec version: 0.25.1
* Contact: contact@skycoin.net
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


@interface OAIApiv1walletsEntriesManagedObjectBuilder : NSObject



-(OAIApiv1walletsEntriesManagedObject*)createNewOAIApiv1walletsEntriesManagedObjectInContext:(NSManagedObjectContext*)context;

-(OAIApiv1walletsEntriesManagedObject*)OAIApiv1walletsEntriesManagedObjectFromOAIApiv1walletsEntries:(OAIApiv1walletsEntries*)object context:(NSManagedObjectContext*)context;

-(void)updateOAIApiv1walletsEntriesManagedObject:(OAIApiv1walletsEntriesManagedObject*)object withOAIApiv1walletsEntries:(OAIApiv1walletsEntries*)object2;

-(OAIApiv1walletsEntries*)OAIApiv1walletsEntriesFromOAIApiv1walletsEntriesManagedObject:(OAIApiv1walletsEntriesManagedObject*)obj;

-(void)updateOAIApiv1walletsEntries:(OAIApiv1walletsEntries*)object withOAIApiv1walletsEntriesManagedObject:(OAIApiv1walletsEntriesManagedObject*)object2;

@end
