

#import "OAIApiv1exploreraddressOutputsManagedObjectBuilder.h"

/**
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

@implementation OAIApiv1exploreraddressOutputsManagedObjectBuilder

-(instancetype)init {
    self = [super init];
    if (self != nil) {
    }
    return self;
}

-(OAIApiv1exploreraddressOutputsManagedObject*)createNewOAIApiv1exploreraddressOutputsManagedObjectInContext:(NSManagedObjectContext*)context {
    OAIApiv1exploreraddressOutputsManagedObject *managedObject = [NSEntityDescription insertNewObjectForEntityForName:NSStringFromClass([OAIApiv1exploreraddressOutputsManagedObject class]) inManagedObjectContext:context];
    return managedObject;
}

-(OAIApiv1exploreraddressOutputsManagedObject*)OAIApiv1exploreraddressOutputsManagedObjectFromOAIApiv1exploreraddressOutputs:(OAIApiv1exploreraddressOutputs*)object context:(NSManagedObjectContext*)context {
    OAIApiv1exploreraddressOutputsManagedObject* newOAIApiv1exploreraddressOutputs = [self createNewOAIApiv1exploreraddressOutputsManagedObjectInContext:context];
    [self updateOAIApiv1exploreraddressOutputsManagedObject:newOAIApiv1exploreraddressOutputs withOAIApiv1exploreraddressOutputs:object];
    return newOAIApiv1exploreraddressOutputs;
}

-(void)updateOAIApiv1exploreraddressOutputsManagedObject:(OAIApiv1exploreraddressOutputsManagedObject*)managedObject withOAIApiv1exploreraddressOutputs:(OAIApiv1exploreraddressOutputs*)object {
    if(!managedObject || !object) {
        return;
    }
    NSManagedObjectContext* context = managedObject.managedObjectContext;
    managedObject.hours = [object.hours copy];
    managedObject.dst = [object.dst copy];
    managedObject.coins = [object.coins copy];
    managedObject.uxid = [object.uxid copy];

}

-(OAIApiv1exploreraddressOutputs*)OAIApiv1exploreraddressOutputsFromOAIApiv1exploreraddressOutputsManagedObject:(OAIApiv1exploreraddressOutputsManagedObject*)obj {
    if(!obj) {
        return nil;
    }
    OAIApiv1exploreraddressOutputs* newOAIApiv1exploreraddressOutputs = [[OAIApiv1exploreraddressOutputs alloc] init];
    [self updateOAIApiv1exploreraddressOutputs:newOAIApiv1exploreraddressOutputs withOAIApiv1exploreraddressOutputsManagedObject:obj];
    return newOAIApiv1exploreraddressOutputs;
}

-(void)updateOAIApiv1exploreraddressOutputs:(OAIApiv1exploreraddressOutputs*)newOAIApiv1exploreraddressOutputs withOAIApiv1exploreraddressOutputsManagedObject:(OAIApiv1exploreraddressOutputsManagedObject*)obj {
    newOAIApiv1exploreraddressOutputs.hours = [obj.hours copy];
    newOAIApiv1exploreraddressOutputs.dst = [obj.dst copy];
    newOAIApiv1exploreraddressOutputs.coins = [obj.coins copy];
    newOAIApiv1exploreraddressOutputs.uxid = [obj.uxid copy];
}

@end
