#import "OAIApiv1wallettransactionWalletManagedObject.h"

/**
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
@implementation OAIApiv1wallettransactionWalletManagedObject

@dynamic unspents;
@dynamic addresses;
@dynamic password;
@dynamic _id;
@end
