#import <Foundation/Foundation.h>
#import <CoreData/CoreData.h>

/**
* Skycoin REST API.
* Skycoin is a next-generation cryptocurrency.
*
* OpenAPI spec version: 0.25.1
* Contact: contact@skycoin.net
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/




NS_ASSUME_NONNULL_BEGIN

@interface OAIApiv1exploreraddressInputsManagedObject : NSManagedObject


@property (nullable, nonatomic, retain) NSString* owner;

@property (nullable, nonatomic, retain) NSNumber* hours;

@property (nullable, nonatomic, retain) NSNumber* calculatedHours;

@property (nullable, nonatomic, retain) NSString* coins;

@property (nullable, nonatomic, retain) NSString* uxid;
@end

@interface OAIApiv1exploreraddressInputsManagedObject (GeneratedAccessors)

@end


NS_ASSUME_NONNULL_END
