#import <Foundation/Foundation.h>
#import <CoreData/CoreData.h>


#import "OAIApiv1wallettransactionHoursSelectionManagedObject.h"
#import "OAIApiv1wallettransactionHoursSelection.h"

/**
* Skycoin REST API.
* Skycoin is a next-generation cryptocurrency.
*
* OpenAPI spec version: 0.25.1
* Contact: contact@skycoin.net
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


@interface OAIApiv1wallettransactionHoursSelectionManagedObjectBuilder : NSObject



-(OAIApiv1wallettransactionHoursSelectionManagedObject*)createNewOAIApiv1wallettransactionHoursSelectionManagedObjectInContext:(NSManagedObjectContext*)context;

-(OAIApiv1wallettransactionHoursSelectionManagedObject*)OAIApiv1wallettransactionHoursSelectionManagedObjectFromOAIApiv1wallettransactionHoursSelection:(OAIApiv1wallettransactionHoursSelection*)object context:(NSManagedObjectContext*)context;

-(void)updateOAIApiv1wallettransactionHoursSelectionManagedObject:(OAIApiv1wallettransactionHoursSelectionManagedObject*)object withOAIApiv1wallettransactionHoursSelection:(OAIApiv1wallettransactionHoursSelection*)object2;

-(OAIApiv1wallettransactionHoursSelection*)OAIApiv1wallettransactionHoursSelectionFromOAIApiv1wallettransactionHoursSelectionManagedObject:(OAIApiv1wallettransactionHoursSelectionManagedObject*)obj;

-(void)updateOAIApiv1wallettransactionHoursSelection:(OAIApiv1wallettransactionHoursSelection*)object withOAIApiv1wallettransactionHoursSelectionManagedObject:(OAIApiv1wallettransactionHoursSelectionManagedObject*)object2;

@end
