

#import "OAIApiv1walletsMetaManagedObjectBuilder.h"

/**
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

@implementation OAIApiv1walletsMetaManagedObjectBuilder

-(instancetype)init {
    self = [super init];
    if (self != nil) {
    }
    return self;
}

-(OAIApiv1walletsMetaManagedObject*)createNewOAIApiv1walletsMetaManagedObjectInContext:(NSManagedObjectContext*)context {
    OAIApiv1walletsMetaManagedObject *managedObject = [NSEntityDescription insertNewObjectForEntityForName:NSStringFromClass([OAIApiv1walletsMetaManagedObject class]) inManagedObjectContext:context];
    return managedObject;
}

-(OAIApiv1walletsMetaManagedObject*)OAIApiv1walletsMetaManagedObjectFromOAIApiv1walletsMeta:(OAIApiv1walletsMeta*)object context:(NSManagedObjectContext*)context {
    OAIApiv1walletsMetaManagedObject* newOAIApiv1walletsMeta = [self createNewOAIApiv1walletsMetaManagedObjectInContext:context];
    [self updateOAIApiv1walletsMetaManagedObject:newOAIApiv1walletsMeta withOAIApiv1walletsMeta:object];
    return newOAIApiv1walletsMeta;
}

-(void)updateOAIApiv1walletsMetaManagedObject:(OAIApiv1walletsMetaManagedObject*)managedObject withOAIApiv1walletsMeta:(OAIApiv1walletsMeta*)object {
    if(!managedObject || !object) {
        return;
    }
    NSManagedObjectContext* context = managedObject.managedObjectContext;
    managedObject.filename = [object.filename copy];
    managedObject.encrypted = [object.encrypted copy];
    managedObject.cryptoType = [object.cryptoType copy];
    managedObject.label = [object.label copy];
    managedObject.type = [object.type copy];
    managedObject.version = [object.version copy];
    managedObject.coin = [object.coin copy];
    managedObject.timestamp = [object.timestamp copy];

}

-(OAIApiv1walletsMeta*)OAIApiv1walletsMetaFromOAIApiv1walletsMetaManagedObject:(OAIApiv1walletsMetaManagedObject*)obj {
    if(!obj) {
        return nil;
    }
    OAIApiv1walletsMeta* newOAIApiv1walletsMeta = [[OAIApiv1walletsMeta alloc] init];
    [self updateOAIApiv1walletsMeta:newOAIApiv1walletsMeta withOAIApiv1walletsMetaManagedObject:obj];
    return newOAIApiv1walletsMeta;
}

-(void)updateOAIApiv1walletsMeta:(OAIApiv1walletsMeta*)newOAIApiv1walletsMeta withOAIApiv1walletsMetaManagedObject:(OAIApiv1walletsMetaManagedObject*)obj {
    newOAIApiv1walletsMeta.filename = [obj.filename copy];
    newOAIApiv1walletsMeta.encrypted = [obj.encrypted copy];
    newOAIApiv1walletsMeta.cryptoType = [obj.cryptoType copy];
    newOAIApiv1walletsMeta.label = [obj.label copy];
    newOAIApiv1walletsMeta.type = [obj.type copy];
    newOAIApiv1walletsMeta.version = [obj.version copy];
    newOAIApiv1walletsMeta.coin = [obj.coin copy];
    newOAIApiv1walletsMeta.timestamp = [obj.timestamp copy];
}

@end
