#import <Foundation/Foundation.h>
#import <CoreData/CoreData.h>


#import "OAIApiv1wallettransactionWalletManagedObject.h"
#import "OAIApiv1wallettransactionWallet.h"

/**
* Skycoin REST API.
* Skycoin is a next-generation cryptocurrency.
*
* OpenAPI spec version: 0.25.1
* Contact: contact@skycoin.net
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


@interface OAIApiv1wallettransactionWalletManagedObjectBuilder : NSObject



-(OAIApiv1wallettransactionWalletManagedObject*)createNewOAIApiv1wallettransactionWalletManagedObjectInContext:(NSManagedObjectContext*)context;

-(OAIApiv1wallettransactionWalletManagedObject*)OAIApiv1wallettransactionWalletManagedObjectFromOAIApiv1wallettransactionWallet:(OAIApiv1wallettransactionWallet*)object context:(NSManagedObjectContext*)context;

-(void)updateOAIApiv1wallettransactionWalletManagedObject:(OAIApiv1wallettransactionWalletManagedObject*)object withOAIApiv1wallettransactionWallet:(OAIApiv1wallettransactionWallet*)object2;

-(OAIApiv1wallettransactionWallet*)OAIApiv1wallettransactionWalletFromOAIApiv1wallettransactionWalletManagedObject:(OAIApiv1wallettransactionWalletManagedObject*)obj;

-(void)updateOAIApiv1wallettransactionWallet:(OAIApiv1wallettransactionWallet*)object withOAIApiv1wallettransactionWalletManagedObject:(OAIApiv1wallettransactionWalletManagedObject*)object2;

@end
