#import <Foundation/Foundation.h>
#import <CoreData/CoreData.h>

/**
* Skycoin REST API.
* Skycoin is a next-generation cryptocurrency.
*
* OpenAPI spec version: 0.25.1
* Contact: contact@skycoin.net
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "OAIApiv1wallettransactionHoursSelectionManagedObject.h"
#import "OAIApiv1wallettransactionToManagedObject.h"
#import "OAIApiv1wallettransactionWalletManagedObject.h"


NS_ASSUME_NONNULL_BEGIN

@interface OAIInlineObjectManagedObject : NSManagedObject


@property (nullable, nonatomic, retain) NSString* changeAddress;

@property (nullable, nonatomic, retain) OAIApiv1wallettransactionHoursSelectionManagedObject* hoursSelection;

@property (nullable, nonatomic, retain) NSNumber* ignoreUnconfirmed;

@property (nullable, nonatomic, retain) NSOrderedSet<OAIApiv1wallettransactionToManagedObject*>* to;

@property (nullable, nonatomic, retain) OAIApiv1wallettransactionWalletManagedObject* wallet;
@end

@interface OAIInlineObjectManagedObject (GeneratedAccessors)
- (void)addToObject:(OAIApiv1wallettransactionToManagedObject *)value;
- (void)removeToObject:(OAIApiv1wallettransactionToManagedObject *)value;
- (void)addTo:(NSOrderedSet<OAIApiv1wallettransactionToManagedObject*> *)values;
- (void)removeTo:(NSOrderedSet<OAIApiv1wallettransactionToManagedObject*> *)values;

@end


NS_ASSUME_NONNULL_END
