#import <Foundation/Foundation.h>
#import <CoreData/CoreData.h>

#import "OAIApiv1wallettransactionHoursSelectionManagedObjectBuilder.h"
#import "OAIApiv1wallettransactionToManagedObjectBuilder.h"
#import "OAIApiv1wallettransactionWalletManagedObjectBuilder.h"

#import "OAIInlineObjectManagedObject.h"
#import "OAIInlineObject.h"

/**
* Skycoin REST API.
* Skycoin is a next-generation cryptocurrency.
*
* OpenAPI spec version: 0.25.1
* Contact: contact@skycoin.net
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


@interface OAIInlineObjectManagedObjectBuilder : NSObject

@property (nonatomic, strong) OAIApiv1wallettransactionHoursSelectionManagedObjectBuilder * hoursSelectionBuilder;
@property (nonatomic, strong) OAIApiv1wallettransactionToManagedObjectBuilder * toBuilder;
@property (nonatomic, strong) OAIApiv1wallettransactionWalletManagedObjectBuilder * walletBuilder;


-(OAIInlineObjectManagedObject*)createNewOAIInlineObjectManagedObjectInContext:(NSManagedObjectContext*)context;

-(OAIInlineObjectManagedObject*)OAIInlineObjectManagedObjectFromOAIInlineObject:(OAIInlineObject*)object context:(NSManagedObjectContext*)context;

-(void)updateOAIInlineObjectManagedObject:(OAIInlineObjectManagedObject*)object withOAIInlineObject:(OAIInlineObject*)object2;

-(OAIInlineObject*)OAIInlineObjectFromOAIInlineObjectManagedObject:(OAIInlineObjectManagedObject*)obj;

-(void)updateOAIInlineObject:(OAIInlineObject*)object withOAIInlineObjectManagedObject:(OAIInlineObjectManagedObject*)object2;

@end
