#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Skycoin REST API.
* Skycoin is a next-generation cryptocurrency.
*
* OpenAPI spec version: 0.25.1
* Contact: contact@skycoin.net
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "OAIInlineResponse2003UnconfirmedVerifyTransaction.h"
@protocol OAIInlineResponse2003UnconfirmedVerifyTransaction;
@class OAIInlineResponse2003UnconfirmedVerifyTransaction;



@protocol OAIInlineResponse2003
@end

@interface OAIInlineResponse2003 : OAIObject


@property(nonatomic) NSNumber* lastReceived;

@property(nonatomic) NSNumber* lastSent;

@property(nonatomic) NSNumber* outgoing;

@property(nonatomic) NSNumber* mirror;

@property(nonatomic) NSString* address;

@property(nonatomic) NSNumber* listenPort;

@property(nonatomic) NSNumber* isTrustedPeer;

@property(nonatomic) NSNumber* connectedAt;

@property(nonatomic) OAIInlineResponse2003UnconfirmedVerifyTransaction* unconfirmedVerifyTransaction;

@property(nonatomic) NSNumber* _id;

@property(nonatomic) NSString* state;

@property(nonatomic) NSString* userAgent;

@property(nonatomic) NSNumber* height;

@end
