

#import "OAIInlineResponse2001ManagedObjectBuilder.h"

/**
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

@implementation OAIInlineResponse2001ManagedObjectBuilder

-(instancetype)init {
    self = [super init];
    if (self != nil) {
    }
    return self;
}

-(OAIInlineResponse2001ManagedObject*)createNewOAIInlineResponse2001ManagedObjectInContext:(NSManagedObjectContext*)context {
    OAIInlineResponse2001ManagedObject *managedObject = [NSEntityDescription insertNewObjectForEntityForName:NSStringFromClass([OAIInlineResponse2001ManagedObject class]) inManagedObjectContext:context];
    return managedObject;
}

-(OAIInlineResponse2001ManagedObject*)OAIInlineResponse2001ManagedObjectFromOAIInlineResponse2001:(OAIInlineResponse2001*)object context:(NSManagedObjectContext*)context {
    OAIInlineResponse2001ManagedObject* newOAIInlineResponse2001 = [self createNewOAIInlineResponse2001ManagedObjectInContext:context];
    [self updateOAIInlineResponse2001ManagedObject:newOAIInlineResponse2001 withOAIInlineResponse2001:object];
    return newOAIInlineResponse2001;
}

-(void)updateOAIInlineResponse2001ManagedObject:(OAIInlineResponse2001ManagedObject*)managedObject withOAIInlineResponse2001:(OAIInlineResponse2001*)object {
    if(!managedObject || !object) {
        return;
    }
    NSManagedObjectContext* context = managedObject.managedObjectContext;
    managedObject.csrfToken = [object.csrfToken copy];

}

-(OAIInlineResponse2001*)OAIInlineResponse2001FromOAIInlineResponse2001ManagedObject:(OAIInlineResponse2001ManagedObject*)obj {
    if(!obj) {
        return nil;
    }
    OAIInlineResponse2001* newOAIInlineResponse2001 = [[OAIInlineResponse2001 alloc] init];
    [self updateOAIInlineResponse2001:newOAIInlineResponse2001 withOAIInlineResponse2001ManagedObject:obj];
    return newOAIInlineResponse2001;
}

-(void)updateOAIInlineResponse2001:(OAIInlineResponse2001*)newOAIInlineResponse2001 withOAIInlineResponse2001ManagedObject:(OAIInlineResponse2001ManagedObject*)obj {
    newOAIInlineResponse2001.csrfToken = [obj.csrfToken copy];
}

@end
