#import "OAIInlineResponse2001ManagedObject.h"

/**
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
@implementation OAIInlineResponse2001ManagedObject

@dynamic csrfToken;
@end
