#import <Foundation/Foundation.h>
#import <CoreData/CoreData.h>

#import "OAIInlineResponse2003UnconfirmedVerifyTransactionManagedObjectBuilder.h"

#import "OAIInlineResponse2003ManagedObject.h"
#import "OAIInlineResponse2003.h"

/**
* Skycoin REST API.
* Skycoin is a next-generation cryptocurrency.
*
* OpenAPI spec version: 0.25.1
* Contact: contact@skycoin.net
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


@interface OAIInlineResponse2003ManagedObjectBuilder : NSObject

@property (nonatomic, strong) OAIInlineResponse2003UnconfirmedVerifyTransactionManagedObjectBuilder * unconfirmedVerifyTransactionBuilder;


-(OAIInlineResponse2003ManagedObject*)createNewOAIInlineResponse2003ManagedObjectInContext:(NSManagedObjectContext*)context;

-(OAIInlineResponse2003ManagedObject*)OAIInlineResponse2003ManagedObjectFromOAIInlineResponse2003:(OAIInlineResponse2003*)object context:(NSManagedObjectContext*)context;

-(void)updateOAIInlineResponse2003ManagedObject:(OAIInlineResponse2003ManagedObject*)object withOAIInlineResponse2003:(OAIInlineResponse2003*)object2;

-(OAIInlineResponse2003*)OAIInlineResponse2003FromOAIInlineResponse2003ManagedObject:(OAIInlineResponse2003ManagedObject*)obj;

-(void)updateOAIInlineResponse2003:(OAIInlineResponse2003*)object withOAIInlineResponse2003ManagedObject:(OAIInlineResponse2003ManagedObject*)object2;

@end
