

#import "OAIInlineResponse2007DataManagedObjectBuilder.h"

/**
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

@implementation OAIInlineResponse2007DataManagedObjectBuilder

-(instancetype)init {
    self = [super init];
    if (self != nil) {
    }
    return self;
}

-(OAIInlineResponse2007DataManagedObject*)createNewOAIInlineResponse2007DataManagedObjectInContext:(NSManagedObjectContext*)context {
    OAIInlineResponse2007DataManagedObject *managedObject = [NSEntityDescription insertNewObjectForEntityForName:NSStringFromClass([OAIInlineResponse2007DataManagedObject class]) inManagedObjectContext:context];
    return managedObject;
}

-(OAIInlineResponse2007DataManagedObject*)OAIInlineResponse2007DataManagedObjectFromOAIInlineResponse2007Data:(OAIInlineResponse2007Data*)object context:(NSManagedObjectContext*)context {
    OAIInlineResponse2007DataManagedObject* newOAIInlineResponse2007Data = [self createNewOAIInlineResponse2007DataManagedObjectInContext:context];
    [self updateOAIInlineResponse2007DataManagedObject:newOAIInlineResponse2007Data withOAIInlineResponse2007Data:object];
    return newOAIInlineResponse2007Data;
}

-(void)updateOAIInlineResponse2007DataManagedObject:(OAIInlineResponse2007DataManagedObject*)managedObject withOAIInlineResponse2007Data:(OAIInlineResponse2007Data*)object {
    if(!managedObject || !object) {
        return;
    }
    NSManagedObjectContext* context = managedObject.managedObjectContext;
    managedObject.version = [object.version copy];

}

-(OAIInlineResponse2007Data*)OAIInlineResponse2007DataFromOAIInlineResponse2007DataManagedObject:(OAIInlineResponse2007DataManagedObject*)obj {
    if(!obj) {
        return nil;
    }
    OAIInlineResponse2007Data* newOAIInlineResponse2007Data = [[OAIInlineResponse2007Data alloc] init];
    [self updateOAIInlineResponse2007Data:newOAIInlineResponse2007Data withOAIInlineResponse2007DataManagedObject:obj];
    return newOAIInlineResponse2007Data;
}

-(void)updateOAIInlineResponse2007Data:(OAIInlineResponse2007Data*)newOAIInlineResponse2007Data withOAIInlineResponse2007DataManagedObject:(OAIInlineResponse2007DataManagedObject*)obj {
    newOAIInlineResponse2007Data.version = [obj.version copy];
}

@end
