

#import "OAIInlineResponseDefaultManagedObjectBuilder.h"

/**
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

@implementation OAIInlineResponseDefaultManagedObjectBuilder

-(instancetype)init {
    self = [super init];
    if (self != nil) {
    }
    return self;
}

-(OAIInlineResponseDefaultManagedObject*)createNewOAIInlineResponseDefaultManagedObjectInContext:(NSManagedObjectContext*)context {
    OAIInlineResponseDefaultManagedObject *managedObject = [NSEntityDescription insertNewObjectForEntityForName:NSStringFromClass([OAIInlineResponseDefaultManagedObject class]) inManagedObjectContext:context];
    return managedObject;
}

-(OAIInlineResponseDefaultManagedObject*)OAIInlineResponseDefaultManagedObjectFromOAIInlineResponseDefault:(OAIInlineResponseDefault*)object context:(NSManagedObjectContext*)context {
    OAIInlineResponseDefaultManagedObject* newOAIInlineResponseDefault = [self createNewOAIInlineResponseDefaultManagedObjectInContext:context];
    [self updateOAIInlineResponseDefaultManagedObject:newOAIInlineResponseDefault withOAIInlineResponseDefault:object];
    return newOAIInlineResponseDefault;
}

-(void)updateOAIInlineResponseDefaultManagedObject:(OAIInlineResponseDefaultManagedObject*)managedObject withOAIInlineResponseDefault:(OAIInlineResponseDefault*)object {
    if(!managedObject || !object) {
        return;
    }
    NSManagedObjectContext* context = managedObject.managedObjectContext;
    managedObject.code = [object.code copy];
    managedObject.message = [object.message copy];

}

-(OAIInlineResponseDefault*)OAIInlineResponseDefaultFromOAIInlineResponseDefaultManagedObject:(OAIInlineResponseDefaultManagedObject*)obj {
    if(!obj) {
        return nil;
    }
    OAIInlineResponseDefault* newOAIInlineResponseDefault = [[OAIInlineResponseDefault alloc] init];
    [self updateOAIInlineResponseDefault:newOAIInlineResponseDefault withOAIInlineResponseDefaultManagedObject:obj];
    return newOAIInlineResponseDefault;
}

-(void)updateOAIInlineResponseDefault:(OAIInlineResponseDefault*)newOAIInlineResponseDefault withOAIInlineResponseDefaultManagedObject:(OAIInlineResponseDefaultManagedObject*)obj {
    newOAIInlineResponseDefault.code = [obj.code copy];
    newOAIInlineResponseDefault.message = [obj.message copy];
}

@end
