#import <Foundation/Foundation.h>
#import <CoreData/CoreData.h>

/**
* Skycoin REST API.
* Skycoin is a next-generation cryptocurrency.
*
* OpenAPI spec version: 0.25.1
* Contact: contact@skycoin.net
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/




NS_ASSUME_NONNULL_BEGIN

@interface OAIInlineResponse2007DataManagedObject : NSManagedObject


@property (nullable, nonatomic, retain) NSNumber* version;
@end

@interface OAIInlineResponse2007DataManagedObject (GeneratedAccessors)

@end


NS_ASSUME_NONNULL_END
