#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Skycoin REST API.
* Skycoin is a next-generation cryptocurrency.
*
* OpenAPI spec version: 0.25.1
* Contact: skycoin.doe@example.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "OAIApiv1walletsEntries.h"
#import "OAIApiv1walletsMeta.h"
@protocol OAIApiv1walletsEntries;
@class OAIApiv1walletsEntries;
@protocol OAIApiv1walletsMeta;
@class OAIApiv1walletsMeta;



@protocol OAIInlineResponse2005
@end

@interface OAIInlineResponse2005 : OAIObject


@property(nonatomic) NSArray<OAIApiv1walletsEntries>* entries;

@property(nonatomic) OAIApiv1walletsMeta* meta;

@end
