

#import "OAIInlineResponse2004ManagedObjectBuilder.h"

/**
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

@implementation OAIInlineResponse2004ManagedObjectBuilder

-(instancetype)init {
    self = [super init];
    if (self != nil) {
       _transactionBuilder = [[OAIApiv1pendingTxsTransactionManagedObjectBuilder alloc] init];
    }
    return self;
}

-(OAIInlineResponse2004ManagedObject*)createNewOAIInlineResponse2004ManagedObjectInContext:(NSManagedObjectContext*)context {
    OAIInlineResponse2004ManagedObject *managedObject = [NSEntityDescription insertNewObjectForEntityForName:NSStringFromClass([OAIInlineResponse2004ManagedObject class]) inManagedObjectContext:context];
    return managedObject;
}

-(OAIInlineResponse2004ManagedObject*)OAIInlineResponse2004ManagedObjectFromOAIInlineResponse2004:(OAIInlineResponse2004*)object context:(NSManagedObjectContext*)context {
    OAIInlineResponse2004ManagedObject* newOAIInlineResponse2004 = [self createNewOAIInlineResponse2004ManagedObjectInContext:context];
    [self updateOAIInlineResponse2004ManagedObject:newOAIInlineResponse2004 withOAIInlineResponse2004:object];
    return newOAIInlineResponse2004;
}

-(void)updateOAIInlineResponse2004ManagedObject:(OAIInlineResponse2004ManagedObject*)managedObject withOAIInlineResponse2004:(OAIInlineResponse2004*)object {
    if(!managedObject || !object) {
        return;
    }
    NSManagedObjectContext* context = managedObject.managedObjectContext;
    managedObject.announced = [object.announced copy];
    managedObject.isValid = [object.isValid copy];
    managedObject.checked = [object.checked copy];
    managedObject.received = [object.received copy];

    if(!managedObject.transaction) {
        managedObject.transaction = [self.transactionBuilder OAIApiv1pendingTxsTransactionManagedObjectFromOAIApiv1pendingTxsTransaction:object.transaction context:managedObject.managedObjectContext];
    } else {
        [self.transactionBuilder updateOAIApiv1pendingTxsTransactionManagedObject:managedObject.transaction withOAIApiv1pendingTxsTransaction:object.transaction];
    }

}

-(OAIInlineResponse2004*)OAIInlineResponse2004FromOAIInlineResponse2004ManagedObject:(OAIInlineResponse2004ManagedObject*)obj {
    if(!obj) {
        return nil;
    }
    OAIInlineResponse2004* newOAIInlineResponse2004 = [[OAIInlineResponse2004 alloc] init];
    [self updateOAIInlineResponse2004:newOAIInlineResponse2004 withOAIInlineResponse2004ManagedObject:obj];
    return newOAIInlineResponse2004;
}

-(void)updateOAIInlineResponse2004:(OAIInlineResponse2004*)newOAIInlineResponse2004 withOAIInlineResponse2004ManagedObject:(OAIInlineResponse2004ManagedObject*)obj {
    newOAIInlineResponse2004.announced = [obj.announced copy];
    newOAIInlineResponse2004.isValid = [obj.isValid copy];
    newOAIInlineResponse2004.checked = [obj.checked copy];
    newOAIInlineResponse2004.received = [obj.received copy];
    newOAIInlineResponse2004.transaction = [self.transactionBuilder OAIApiv1pendingTxsTransactionFromOAIApiv1pendingTxsTransactionManagedObject:obj.transaction];
}

@end
