#import "OAIInlineResponse2006ManagedObject.h"

/**
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
@implementation OAIInlineResponse2006ManagedObject

@dynamic address;
@end
