#import <Foundation/Foundation.h>
#import <CoreData/CoreData.h>

/**
* Skycoin REST API.
* Skycoin is a next-generation cryptocurrency.
*
* OpenAPI spec version: 0.25.1
* Contact: contact@skycoin.net
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "OAIApiv1walletsEntriesManagedObject.h"
#import "OAIApiv1walletsMetaManagedObject.h"


NS_ASSUME_NONNULL_BEGIN

@interface OAIInlineResponse2005ManagedObject : NSManagedObject


@property (nullable, nonatomic, retain) NSOrderedSet<OAIApiv1walletsEntriesManagedObject*>* entries;

@property (nullable, nonatomic, retain) OAIApiv1walletsMetaManagedObject* meta;
@end

@interface OAIInlineResponse2005ManagedObject (GeneratedAccessors)
- (void)addEntriesObject:(OAIApiv1walletsEntriesManagedObject *)value;
- (void)removeEntriesObject:(OAIApiv1walletsEntriesManagedObject *)value;
- (void)addEntries:(NSOrderedSet<OAIApiv1walletsEntriesManagedObject*> *)values;
- (void)removeEntries:(NSOrderedSet<OAIApiv1walletsEntriesManagedObject*> *)values;

@end


NS_ASSUME_NONNULL_END
