#import <Foundation/Foundation.h>
#import <CoreData/CoreData.h>

/**
* Skycoin REST API.
* Skycoin is a next-generation cryptocurrency.
*
* OpenAPI spec version: 0.25.1
* Contact: contact@skycoin.net
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/




NS_ASSUME_NONNULL_BEGIN

@interface OAIInlineResponse200ManagedObject : NSManagedObject


@property (nullable, nonatomic, retain) NSNumber* hours;

@property (nullable, nonatomic, retain) NSNumber* coins;

@property (nullable, nonatomic, retain) NSString* uxid;

@property (nullable, nonatomic, retain) NSString* ownerAddress;

@property (nullable, nonatomic, retain) NSNumber* spentBlockSeq;

@property (nullable, nonatomic, retain) NSString* spentTx;

@property (nullable, nonatomic, retain) NSNumber* time;

@property (nullable, nonatomic, retain) NSNumber* srcBlockSeq;

@property (nullable, nonatomic, retain) NSString* srcTx;
@end

@interface OAIInlineResponse200ManagedObject (GeneratedAccessors)

@end


NS_ASSUME_NONNULL_END
