#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Skycoin REST API.
* Skycoin is a next-generation cryptocurrency.
*
* OpenAPI spec version: 0.25.1
* Contact: skycoin.doe@example.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "OAIApiv1pendingTxsTransaction.h"
@protocol OAIApiv1pendingTxsTransaction;
@class OAIApiv1pendingTxsTransaction;



@protocol OAIInlineResponse2004
@end

@interface OAIInlineResponse2004 : OAIObject


@property(nonatomic) NSString* announced;

@property(nonatomic) NSNumber* isValid;

@property(nonatomic) NSString* checked;

@property(nonatomic) NSString* received;

@property(nonatomic) OAIApiv1pendingTxsTransaction* transaction;

@end
