#import <Foundation/Foundation.h>
#import <CoreData/CoreData.h>

/**
* Skycoin REST API.
* Skycoin is a next-generation cryptocurrency.
*
* OpenAPI spec version: 0.25.1
* Contact: contact@skycoin.net
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "OAIInlineResponse2003UnconfirmedVerifyTransactionManagedObject.h"


NS_ASSUME_NONNULL_BEGIN

@interface OAIInlineResponse2003ManagedObject : NSManagedObject


@property (nullable, nonatomic, retain) NSNumber* lastReceived;

@property (nullable, nonatomic, retain) NSNumber* lastSent;

@property (nullable, nonatomic, retain) NSNumber* outgoing;

@property (nullable, nonatomic, retain) NSNumber* mirror;

@property (nullable, nonatomic, retain) NSString* address;

@property (nullable, nonatomic, retain) NSNumber* listenPort;

@property (nullable, nonatomic, retain) NSNumber* isTrustedPeer;

@property (nullable, nonatomic, retain) NSNumber* connectedAt;

@property (nullable, nonatomic, retain) OAIInlineResponse2003UnconfirmedVerifyTransactionManagedObject* unconfirmedVerifyTransaction;

@property (nullable, nonatomic, retain) NSNumber* _id;

@property (nullable, nonatomic, retain) NSString* state;

@property (nullable, nonatomic, retain) NSString* userAgent;

@property (nullable, nonatomic, retain) NSNumber* height;
@end

@interface OAIInlineResponse2003ManagedObject (GeneratedAccessors)

@end


NS_ASSUME_NONNULL_END
