#import <Foundation/Foundation.h>
#import <CoreData/CoreData.h>

#import "OAIApiv1walletsEntriesManagedObjectBuilder.h"
#import "OAIApiv1walletsMetaManagedObjectBuilder.h"

#import "OAIInlineResponse2005ManagedObject.h"
#import "OAIInlineResponse2005.h"

/**
* Skycoin REST API.
* Skycoin is a next-generation cryptocurrency.
*
* OpenAPI spec version: 0.25.1
* Contact: contact@skycoin.net
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


@interface OAIInlineResponse2005ManagedObjectBuilder : NSObject

@property (nonatomic, strong) OAIApiv1walletsEntriesManagedObjectBuilder * entriesBuilder;
@property (nonatomic, strong) OAIApiv1walletsMetaManagedObjectBuilder * metaBuilder;


-(OAIInlineResponse2005ManagedObject*)createNewOAIInlineResponse2005ManagedObjectInContext:(NSManagedObjectContext*)context;

-(OAIInlineResponse2005ManagedObject*)OAIInlineResponse2005ManagedObjectFromOAIInlineResponse2005:(OAIInlineResponse2005*)object context:(NSManagedObjectContext*)context;

-(void)updateOAIInlineResponse2005ManagedObject:(OAIInlineResponse2005ManagedObject*)object withOAIInlineResponse2005:(OAIInlineResponse2005*)object2;

-(OAIInlineResponse2005*)OAIInlineResponse2005FromOAIInlineResponse2005ManagedObject:(OAIInlineResponse2005ManagedObject*)obj;

-(void)updateOAIInlineResponse2005:(OAIInlineResponse2005*)object withOAIInlineResponse2005ManagedObject:(OAIInlineResponse2005ManagedObject*)object2;

@end
