#import "OAIInlineResponse2005ManagedObject.h"

/**
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
@implementation OAIInlineResponse2005ManagedObject

@dynamic entries;
@dynamic meta;
@end
