#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Skycoin REST API.
* Skycoin is a next-generation cryptocurrency.
*
* OpenAPI spec version: 0.25.1
* Contact: skycoin.doe@example.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol OAIInlineResponse200
@end

@interface OAIInlineResponse200 : OAIObject


@property(nonatomic) NSNumber* hours;

@property(nonatomic) NSNumber* coins;

@property(nonatomic) NSString* uxid;

@property(nonatomic) NSString* ownerAddress;

@property(nonatomic) NSNumber* spentBlockSeq;

@property(nonatomic) NSString* spentTx;

@property(nonatomic) NSNumber* time;

@property(nonatomic) NSNumber* srcBlockSeq;

@property(nonatomic) NSString* srcTx;

@end
