#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Skycoin REST API.
* Skycoin is a next-generation cryptocurrency.
*
* OpenAPI spec version: 0.25.1
* Contact: skycoin.doe@example.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "OAIApiv1wallettransactionHoursSelection.h"
#import "OAIApiv1wallettransactionTo.h"
#import "OAIApiv1wallettransactionWallet.h"
@protocol OAIApiv1wallettransactionHoursSelection;
@class OAIApiv1wallettransactionHoursSelection;
@protocol OAIApiv1wallettransactionTo;
@class OAIApiv1wallettransactionTo;
@protocol OAIApiv1wallettransactionWallet;
@class OAIApiv1wallettransactionWallet;



@protocol OAIInlineObject
@end

@interface OAIInlineObject : OAIObject


@property(nonatomic) NSString* changeAddress;

@property(nonatomic) OAIApiv1wallettransactionHoursSelection* hoursSelection;

@property(nonatomic) NSNumber* ignoreUnconfirmed;

@property(nonatomic) NSArray<OAIApiv1wallettransactionTo>* to;

@property(nonatomic) OAIApiv1wallettransactionWallet* wallet;

@end
