

#import "OAIInlineResponse2007ManagedObjectBuilder.h"

/**
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

@implementation OAIInlineResponse2007ManagedObjectBuilder

-(instancetype)init {
    self = [super init];
    if (self != nil) {
       _dataBuilder = [[OAIInlineResponse2007DataManagedObjectBuilder alloc] init];
    }
    return self;
}

-(OAIInlineResponse2007ManagedObject*)createNewOAIInlineResponse2007ManagedObjectInContext:(NSManagedObjectContext*)context {
    OAIInlineResponse2007ManagedObject *managedObject = [NSEntityDescription insertNewObjectForEntityForName:NSStringFromClass([OAIInlineResponse2007ManagedObject class]) inManagedObjectContext:context];
    return managedObject;
}

-(OAIInlineResponse2007ManagedObject*)OAIInlineResponse2007ManagedObjectFromOAIInlineResponse2007:(OAIInlineResponse2007*)object context:(NSManagedObjectContext*)context {
    OAIInlineResponse2007ManagedObject* newOAIInlineResponse2007 = [self createNewOAIInlineResponse2007ManagedObjectInContext:context];
    [self updateOAIInlineResponse2007ManagedObject:newOAIInlineResponse2007 withOAIInlineResponse2007:object];
    return newOAIInlineResponse2007;
}

-(void)updateOAIInlineResponse2007ManagedObject:(OAIInlineResponse2007ManagedObject*)managedObject withOAIInlineResponse2007:(OAIInlineResponse2007*)object {
    if(!managedObject || !object) {
        return;
    }
    NSManagedObjectContext* context = managedObject.managedObjectContext;

    if(!managedObject.data) {
        managedObject.data = [self.dataBuilder OAIInlineResponse2007DataManagedObjectFromOAIInlineResponse2007Data:object.data context:managedObject.managedObjectContext];
    } else {
        [self.dataBuilder updateOAIInlineResponse2007DataManagedObject:managedObject.data withOAIInlineResponse2007Data:object.data];
    }
    managedObject.error = [object.error copy];

}

-(OAIInlineResponse2007*)OAIInlineResponse2007FromOAIInlineResponse2007ManagedObject:(OAIInlineResponse2007ManagedObject*)obj {
    if(!obj) {
        return nil;
    }
    OAIInlineResponse2007* newOAIInlineResponse2007 = [[OAIInlineResponse2007 alloc] init];
    [self updateOAIInlineResponse2007:newOAIInlineResponse2007 withOAIInlineResponse2007ManagedObject:obj];
    return newOAIInlineResponse2007;
}

-(void)updateOAIInlineResponse2007:(OAIInlineResponse2007*)newOAIInlineResponse2007 withOAIInlineResponse2007ManagedObject:(OAIInlineResponse2007ManagedObject*)obj {
    newOAIInlineResponse2007.data = [self.dataBuilder OAIInlineResponse2007DataFromOAIInlineResponse2007DataManagedObject:obj.data];
    newOAIInlineResponse2007.error = [obj.error copy];
}

@end
