

#import "OAIInlineResponse2006ManagedObjectBuilder.h"

/**
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

@implementation OAIInlineResponse2006ManagedObjectBuilder

-(instancetype)init {
    self = [super init];
    if (self != nil) {
    }
    return self;
}

-(OAIInlineResponse2006ManagedObject*)createNewOAIInlineResponse2006ManagedObjectInContext:(NSManagedObjectContext*)context {
    OAIInlineResponse2006ManagedObject *managedObject = [NSEntityDescription insertNewObjectForEntityForName:NSStringFromClass([OAIInlineResponse2006ManagedObject class]) inManagedObjectContext:context];
    return managedObject;
}

-(OAIInlineResponse2006ManagedObject*)OAIInlineResponse2006ManagedObjectFromOAIInlineResponse2006:(OAIInlineResponse2006*)object context:(NSManagedObjectContext*)context {
    OAIInlineResponse2006ManagedObject* newOAIInlineResponse2006 = [self createNewOAIInlineResponse2006ManagedObjectInContext:context];
    [self updateOAIInlineResponse2006ManagedObject:newOAIInlineResponse2006 withOAIInlineResponse2006:object];
    return newOAIInlineResponse2006;
}

-(void)updateOAIInlineResponse2006ManagedObject:(OAIInlineResponse2006ManagedObject*)managedObject withOAIInlineResponse2006:(OAIInlineResponse2006*)object {
    if(!managedObject || !object) {
        return;
    }
    NSManagedObjectContext* context = managedObject.managedObjectContext;
    managedObject.address = [object.address copy];

}

-(OAIInlineResponse2006*)OAIInlineResponse2006FromOAIInlineResponse2006ManagedObject:(OAIInlineResponse2006ManagedObject*)obj {
    if(!obj) {
        return nil;
    }
    OAIInlineResponse2006* newOAIInlineResponse2006 = [[OAIInlineResponse2006 alloc] init];
    [self updateOAIInlineResponse2006:newOAIInlineResponse2006 withOAIInlineResponse2006ManagedObject:obj];
    return newOAIInlineResponse2006;
}

-(void)updateOAIInlineResponse2006:(OAIInlineResponse2006*)newOAIInlineResponse2006 withOAIInlineResponse2006ManagedObject:(OAIInlineResponse2006ManagedObject*)obj {
    newOAIInlineResponse2006.address = [obj.address copy];
}

@end
