#import <Foundation/Foundation.h>
#import <CoreData/CoreData.h>


#import "OAIInlineResponse2006ManagedObject.h"
#import "OAIInlineResponse2006.h"

/**
* Skycoin REST API.
* Skycoin is a next-generation cryptocurrency.
*
* OpenAPI spec version: 0.25.1
* Contact: contact@skycoin.net
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


@interface OAIInlineResponse2006ManagedObjectBuilder : NSObject



-(OAIInlineResponse2006ManagedObject*)createNewOAIInlineResponse2006ManagedObjectInContext:(NSManagedObjectContext*)context;

-(OAIInlineResponse2006ManagedObject*)OAIInlineResponse2006ManagedObjectFromOAIInlineResponse2006:(OAIInlineResponse2006*)object context:(NSManagedObjectContext*)context;

-(void)updateOAIInlineResponse2006ManagedObject:(OAIInlineResponse2006ManagedObject*)object withOAIInlineResponse2006:(OAIInlineResponse2006*)object2;

-(OAIInlineResponse2006*)OAIInlineResponse2006FromOAIInlineResponse2006ManagedObject:(OAIInlineResponse2006ManagedObject*)obj;

-(void)updateOAIInlineResponse2006:(OAIInlineResponse2006*)object withOAIInlineResponse2006ManagedObject:(OAIInlineResponse2006ManagedObject*)object2;

@end
