#import <Foundation/Foundation.h>
#import <CoreData/CoreData.h>

#import "OAIApiv1pendingTxsTransactionManagedObjectBuilder.h"

#import "OAIInlineResponse2004ManagedObject.h"
#import "OAIInlineResponse2004.h"

/**
* Skycoin REST API.
* Skycoin is a next-generation cryptocurrency.
*
* OpenAPI spec version: 0.25.1
* Contact: contact@skycoin.net
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


@interface OAIInlineResponse2004ManagedObjectBuilder : NSObject

@property (nonatomic, strong) OAIApiv1pendingTxsTransactionManagedObjectBuilder * transactionBuilder;


-(OAIInlineResponse2004ManagedObject*)createNewOAIInlineResponse2004ManagedObjectInContext:(NSManagedObjectContext*)context;

-(OAIInlineResponse2004ManagedObject*)OAIInlineResponse2004ManagedObjectFromOAIInlineResponse2004:(OAIInlineResponse2004*)object context:(NSManagedObjectContext*)context;

-(void)updateOAIInlineResponse2004ManagedObject:(OAIInlineResponse2004ManagedObject*)object withOAIInlineResponse2004:(OAIInlineResponse2004*)object2;

-(OAIInlineResponse2004*)OAIInlineResponse2004FromOAIInlineResponse2004ManagedObject:(OAIInlineResponse2004ManagedObject*)obj;

-(void)updateOAIInlineResponse2004:(OAIInlineResponse2004*)object withOAIInlineResponse2004ManagedObject:(OAIInlineResponse2004ManagedObject*)object2;

@end
