#import "OAIInlineResponse200ManagedObject.h"

/**
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
@implementation OAIInlineResponse200ManagedObject

@dynamic hours;
@dynamic coins;
@dynamic uxid;
@dynamic ownerAddress;
@dynamic spentBlockSeq;
@dynamic spentTx;
@dynamic time;
@dynamic srcBlockSeq;
@dynamic srcTx;
@end
