#import <Foundation/Foundation.h>
#import <CoreData/CoreData.h>

/**
* Skycoin REST API.
* Skycoin is a next-generation cryptocurrency.
*
* OpenAPI spec version: 0.25.1
* Contact: contact@skycoin.net
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "OAIApiv1pendingTxsTransactionManagedObject.h"


NS_ASSUME_NONNULL_BEGIN

@interface OAIInlineResponse2004ManagedObject : NSManagedObject


@property (nullable, nonatomic, retain) NSString* announced;

@property (nullable, nonatomic, retain) NSNumber* isValid;

@property (nullable, nonatomic, retain) NSString* checked;

@property (nullable, nonatomic, retain) NSString* received;

@property (nullable, nonatomic, retain) OAIApiv1pendingTxsTransactionManagedObject* transaction;
@end

@interface OAIInlineResponse2004ManagedObject (GeneratedAccessors)

@end


NS_ASSUME_NONNULL_END
