#import <Foundation/Foundation.h>
#import <CoreData/CoreData.h>


#import "OAIInlineResponse2003UnconfirmedVerifyTransactionManagedObject.h"
#import "OAIInlineResponse2003UnconfirmedVerifyTransaction.h"

/**
* Skycoin REST API.
* Skycoin is a next-generation cryptocurrency.
*
* OpenAPI spec version: 0.25.1
* Contact: contact@skycoin.net
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


@interface OAIInlineResponse2003UnconfirmedVerifyTransactionManagedObjectBuilder : NSObject



-(OAIInlineResponse2003UnconfirmedVerifyTransactionManagedObject*)createNewOAIInlineResponse2003UnconfirmedVerifyTransactionManagedObjectInContext:(NSManagedObjectContext*)context;

-(OAIInlineResponse2003UnconfirmedVerifyTransactionManagedObject*)OAIInlineResponse2003UnconfirmedVerifyTransactionManagedObjectFromOAIInlineResponse2003UnconfirmedVerifyTransaction:(OAIInlineResponse2003UnconfirmedVerifyTransaction*)object context:(NSManagedObjectContext*)context;

-(void)updateOAIInlineResponse2003UnconfirmedVerifyTransactionManagedObject:(OAIInlineResponse2003UnconfirmedVerifyTransactionManagedObject*)object withOAIInlineResponse2003UnconfirmedVerifyTransaction:(OAIInlineResponse2003UnconfirmedVerifyTransaction*)object2;

-(OAIInlineResponse2003UnconfirmedVerifyTransaction*)OAIInlineResponse2003UnconfirmedVerifyTransactionFromOAIInlineResponse2003UnconfirmedVerifyTransactionManagedObject:(OAIInlineResponse2003UnconfirmedVerifyTransactionManagedObject*)obj;

-(void)updateOAIInlineResponse2003UnconfirmedVerifyTransaction:(OAIInlineResponse2003UnconfirmedVerifyTransaction*)object withOAIInlineResponse2003UnconfirmedVerifyTransactionManagedObject:(OAIInlineResponse2003UnconfirmedVerifyTransactionManagedObject*)object2;

@end
