#import "OAIInlineResponse2003UnconfirmedVerifyTransactionManagedObject.h"

/**
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
@implementation OAIInlineResponse2003UnconfirmedVerifyTransactionManagedObject

@dynamic burnFactor;
@dynamic maxTransactionSize;
@dynamic maxDecimals;
@end
