#import <Foundation/Foundation.h>
#import <CoreData/CoreData.h>


#import "OAIInlineResponseDefaultManagedObject.h"
#import "OAIInlineResponseDefault.h"

/**
* Skycoin REST API.
* Skycoin is a next-generation cryptocurrency.
*
* OpenAPI spec version: 0.25.1
* Contact: contact@skycoin.net
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


@interface OAIInlineResponseDefaultManagedObjectBuilder : NSObject



-(OAIInlineResponseDefaultManagedObject*)createNewOAIInlineResponseDefaultManagedObjectInContext:(NSManagedObjectContext*)context;

-(OAIInlineResponseDefaultManagedObject*)OAIInlineResponseDefaultManagedObjectFromOAIInlineResponseDefault:(OAIInlineResponseDefault*)object context:(NSManagedObjectContext*)context;

-(void)updateOAIInlineResponseDefaultManagedObject:(OAIInlineResponseDefaultManagedObject*)object withOAIInlineResponseDefault:(OAIInlineResponseDefault*)object2;

-(OAIInlineResponseDefault*)OAIInlineResponseDefaultFromOAIInlineResponseDefaultManagedObject:(OAIInlineResponseDefaultManagedObject*)obj;

-(void)updateOAIInlineResponseDefault:(OAIInlineResponseDefault*)object withOAIInlineResponseDefaultManagedObject:(OAIInlineResponseDefaultManagedObject*)object2;

@end
