#import "OAIInlineResponse2002ManagedObject.h"

/**
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
@implementation OAIInlineResponse2002ManagedObject

@dynamic outputs;
@dynamic innerHash;
@dynamic inputs;
@dynamic fee;
@dynamic sigs;
@dynamic length;
@dynamic txid;
@dynamic type;
@dynamic status;
@dynamic timestamp;
@end
