#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Skycoin REST API.
* Skycoin is a next-generation cryptocurrency.
*
* OpenAPI spec version: 0.25.1
* Contact: contact@skycoin.net
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol OAIInlineResponse2003UnconfirmedVerifyTransaction
@end

@interface OAIInlineResponse2003UnconfirmedVerifyTransaction : OAIObject


@property(nonatomic) NSNumber* burnFactor;

@property(nonatomic) NSNumber* maxTransactionSize;

@property(nonatomic) NSNumber* maxDecimals;

@end
