#import <Foundation/Foundation.h>
#import <CoreData/CoreData.h>


#import "OAIInlineResponse200ManagedObject.h"
#import "OAIInlineResponse200.h"

/**
* Skycoin REST API.
* Skycoin is a next-generation cryptocurrency.
*
* OpenAPI spec version: 0.25.1
* Contact: contact@skycoin.net
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


@interface OAIInlineResponse200ManagedObjectBuilder : NSObject



-(OAIInlineResponse200ManagedObject*)createNewOAIInlineResponse200ManagedObjectInContext:(NSManagedObjectContext*)context;

-(OAIInlineResponse200ManagedObject*)OAIInlineResponse200ManagedObjectFromOAIInlineResponse200:(OAIInlineResponse200*)object context:(NSManagedObjectContext*)context;

-(void)updateOAIInlineResponse200ManagedObject:(OAIInlineResponse200ManagedObject*)object withOAIInlineResponse200:(OAIInlineResponse200*)object2;

-(OAIInlineResponse200*)OAIInlineResponse200FromOAIInlineResponse200ManagedObject:(OAIInlineResponse200ManagedObject*)obj;

-(void)updateOAIInlineResponse200:(OAIInlineResponse200*)object withOAIInlineResponse200ManagedObject:(OAIInlineResponse200ManagedObject*)object2;

@end
