#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Skycoin REST API.
* Skycoin is a next-generation cryptocurrency.
*
* OpenAPI spec version: 0.25.1
* Contact: skycoin.doe@example.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "OAIApiv1exploreraddressInputs.h"
#import "OAIApiv1exploreraddressOutputs.h"
#import "OAIApiv1exploreraddressStatus.h"
@protocol OAIApiv1exploreraddressInputs;
@class OAIApiv1exploreraddressInputs;
@protocol OAIApiv1exploreraddressOutputs;
@class OAIApiv1exploreraddressOutputs;
@protocol OAIApiv1exploreraddressStatus;
@class OAIApiv1exploreraddressStatus;



@protocol OAIInlineResponse2002
@end

@interface OAIInlineResponse2002 : OAIObject


@property(nonatomic) NSArray<OAIApiv1exploreraddressOutputs>* outputs;

@property(nonatomic) NSString* innerHash;

@property(nonatomic) NSArray<OAIApiv1exploreraddressInputs>* inputs;

@property(nonatomic) NSNumber* fee;

@property(nonatomic) NSArray<NSString*>* sigs;

@property(nonatomic) NSNumber* length;

@property(nonatomic) NSString* txid;

@property(nonatomic) NSNumber* type;

@property(nonatomic) OAIApiv1exploreraddressStatus* status;

@property(nonatomic) NSNumber* timestamp;

@end
