#import "OAIInlineResponse2003ManagedObject.h"

/**
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
@implementation OAIInlineResponse2003ManagedObject

@dynamic lastReceived;
@dynamic lastSent;
@dynamic outgoing;
@dynamic mirror;
@dynamic address;
@dynamic listenPort;
@dynamic isTrustedPeer;
@dynamic connectedAt;
@dynamic unconfirmedVerifyTransaction;
@dynamic _id;
@dynamic state;
@dynamic userAgent;
@dynamic height;
@end
