#import "OAIInlineResponse2007ManagedObject.h"

/**
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
@implementation OAIInlineResponse2007ManagedObject

@dynamic data;
@dynamic error;
@end
