#import <Foundation/Foundation.h>
#import <CoreData/CoreData.h>


#import "OAIInlineResponse2007DataManagedObject.h"
#import "OAIInlineResponse2007Data.h"

/**
* Skycoin REST API.
* Skycoin is a next-generation cryptocurrency.
*
* OpenAPI spec version: 0.25.1
* Contact: contact@skycoin.net
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


@interface OAIInlineResponse2007DataManagedObjectBuilder : NSObject



-(OAIInlineResponse2007DataManagedObject*)createNewOAIInlineResponse2007DataManagedObjectInContext:(NSManagedObjectContext*)context;

-(OAIInlineResponse2007DataManagedObject*)OAIInlineResponse2007DataManagedObjectFromOAIInlineResponse2007Data:(OAIInlineResponse2007Data*)object context:(NSManagedObjectContext*)context;

-(void)updateOAIInlineResponse2007DataManagedObject:(OAIInlineResponse2007DataManagedObject*)object withOAIInlineResponse2007Data:(OAIInlineResponse2007Data*)object2;

-(OAIInlineResponse2007Data*)OAIInlineResponse2007DataFromOAIInlineResponse2007DataManagedObject:(OAIInlineResponse2007DataManagedObject*)obj;

-(void)updateOAIInlineResponse2007Data:(OAIInlineResponse2007Data*)object withOAIInlineResponse2007DataManagedObject:(OAIInlineResponse2007DataManagedObject*)object2;

@end
