#import "OAIInlineResponse2004ManagedObject.h"

/**
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
@implementation OAIInlineResponse2004ManagedObject

@dynamic announced;
@dynamic isValid;
@dynamic checked;
@dynamic received;
@dynamic transaction;
@end
