#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Skycoin REST API.
* Skycoin is a next-generation cryptocurrency.
*
* OpenAPI spec version: 0.25.1
* Contact: contact@skycoin.net
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "OAIInlineResponse2007Data.h"
@protocol OAIInlineResponse2007Data;
@class OAIInlineResponse2007Data;



@protocol OAIInlineResponse2007
@end

@interface OAIInlineResponse2007 : OAIObject


@property(nonatomic) OAIInlineResponse2007Data* data;

@property(nonatomic) NSObject* error;

@end
