#import <Foundation/Foundation.h>
#import <CoreData/CoreData.h>

#import "OAIApiv1exploreraddressInputsManagedObjectBuilder.h"
#import "OAIApiv1exploreraddressOutputsManagedObjectBuilder.h"
#import "OAIApiv1exploreraddressStatusManagedObjectBuilder.h"

#import "OAIInlineResponse2002ManagedObject.h"
#import "OAIInlineResponse2002.h"

/**
* Skycoin REST API.
* Skycoin is a next-generation cryptocurrency.
*
* OpenAPI spec version: 0.25.1
* Contact: contact@skycoin.net
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


@interface OAIInlineResponse2002ManagedObjectBuilder : NSObject

@property (nonatomic, strong) OAIApiv1exploreraddressOutputsManagedObjectBuilder * outputsBuilder;
@property (nonatomic, strong) OAIApiv1exploreraddressInputsManagedObjectBuilder * inputsBuilder;
@property (nonatomic, strong) OAIApiv1exploreraddressStatusManagedObjectBuilder * statusBuilder;


-(OAIInlineResponse2002ManagedObject*)createNewOAIInlineResponse2002ManagedObjectInContext:(NSManagedObjectContext*)context;

-(OAIInlineResponse2002ManagedObject*)OAIInlineResponse2002ManagedObjectFromOAIInlineResponse2002:(OAIInlineResponse2002*)object context:(NSManagedObjectContext*)context;

-(void)updateOAIInlineResponse2002ManagedObject:(OAIInlineResponse2002ManagedObject*)object withOAIInlineResponse2002:(OAIInlineResponse2002*)object2;

-(OAIInlineResponse2002*)OAIInlineResponse2002FromOAIInlineResponse2002ManagedObject:(OAIInlineResponse2002ManagedObject*)obj;

-(void)updateOAIInlineResponse2002:(OAIInlineResponse2002*)object withOAIInlineResponse2002ManagedObject:(OAIInlineResponse2002ManagedObject*)object2;

@end
