

#import "OAIInlineResponse2003ManagedObjectBuilder.h"

/**
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

@implementation OAIInlineResponse2003ManagedObjectBuilder

-(instancetype)init {
    self = [super init];
    if (self != nil) {
       _unconfirmedVerifyTransactionBuilder = [[OAIInlineResponse2003UnconfirmedVerifyTransactionManagedObjectBuilder alloc] init];
    }
    return self;
}

-(OAIInlineResponse2003ManagedObject*)createNewOAIInlineResponse2003ManagedObjectInContext:(NSManagedObjectContext*)context {
    OAIInlineResponse2003ManagedObject *managedObject = [NSEntityDescription insertNewObjectForEntityForName:NSStringFromClass([OAIInlineResponse2003ManagedObject class]) inManagedObjectContext:context];
    return managedObject;
}

-(OAIInlineResponse2003ManagedObject*)OAIInlineResponse2003ManagedObjectFromOAIInlineResponse2003:(OAIInlineResponse2003*)object context:(NSManagedObjectContext*)context {
    OAIInlineResponse2003ManagedObject* newOAIInlineResponse2003 = [self createNewOAIInlineResponse2003ManagedObjectInContext:context];
    [self updateOAIInlineResponse2003ManagedObject:newOAIInlineResponse2003 withOAIInlineResponse2003:object];
    return newOAIInlineResponse2003;
}

-(void)updateOAIInlineResponse2003ManagedObject:(OAIInlineResponse2003ManagedObject*)managedObject withOAIInlineResponse2003:(OAIInlineResponse2003*)object {
    if(!managedObject || !object) {
        return;
    }
    NSManagedObjectContext* context = managedObject.managedObjectContext;
    managedObject.lastReceived = [object.lastReceived copy];
    managedObject.lastSent = [object.lastSent copy];
    managedObject.outgoing = [object.outgoing copy];
    managedObject.mirror = [object.mirror copy];
    managedObject.address = [object.address copy];
    managedObject.listenPort = [object.listenPort copy];
    managedObject.isTrustedPeer = [object.isTrustedPeer copy];
    managedObject.connectedAt = [object.connectedAt copy];

    if(!managedObject.unconfirmedVerifyTransaction) {
        managedObject.unconfirmedVerifyTransaction = [self.unconfirmedVerifyTransactionBuilder OAIInlineResponse2003UnconfirmedVerifyTransactionManagedObjectFromOAIInlineResponse2003UnconfirmedVerifyTransaction:object.unconfirmedVerifyTransaction context:managedObject.managedObjectContext];
    } else {
        [self.unconfirmedVerifyTransactionBuilder updateOAIInlineResponse2003UnconfirmedVerifyTransactionManagedObject:managedObject.unconfirmedVerifyTransaction withOAIInlineResponse2003UnconfirmedVerifyTransaction:object.unconfirmedVerifyTransaction];
    }
    managedObject._id = [object._id copy];
    managedObject.state = [object.state copy];
    managedObject.userAgent = [object.userAgent copy];
    managedObject.height = [object.height copy];

}

-(OAIInlineResponse2003*)OAIInlineResponse2003FromOAIInlineResponse2003ManagedObject:(OAIInlineResponse2003ManagedObject*)obj {
    if(!obj) {
        return nil;
    }
    OAIInlineResponse2003* newOAIInlineResponse2003 = [[OAIInlineResponse2003 alloc] init];
    [self updateOAIInlineResponse2003:newOAIInlineResponse2003 withOAIInlineResponse2003ManagedObject:obj];
    return newOAIInlineResponse2003;
}

-(void)updateOAIInlineResponse2003:(OAIInlineResponse2003*)newOAIInlineResponse2003 withOAIInlineResponse2003ManagedObject:(OAIInlineResponse2003ManagedObject*)obj {
    newOAIInlineResponse2003.lastReceived = [obj.lastReceived copy];
    newOAIInlineResponse2003.lastSent = [obj.lastSent copy];
    newOAIInlineResponse2003.outgoing = [obj.outgoing copy];
    newOAIInlineResponse2003.mirror = [obj.mirror copy];
    newOAIInlineResponse2003.address = [obj.address copy];
    newOAIInlineResponse2003.listenPort = [obj.listenPort copy];
    newOAIInlineResponse2003.isTrustedPeer = [obj.isTrustedPeer copy];
    newOAIInlineResponse2003.connectedAt = [obj.connectedAt copy];
    newOAIInlineResponse2003.unconfirmedVerifyTransaction = [self.unconfirmedVerifyTransactionBuilder OAIInlineResponse2003UnconfirmedVerifyTransactionFromOAIInlineResponse2003UnconfirmedVerifyTransactionManagedObject:obj.unconfirmedVerifyTransaction];
    newOAIInlineResponse2003._id = [obj._id copy];
    newOAIInlineResponse2003.state = [obj.state copy];
    newOAIInlineResponse2003.userAgent = [obj.userAgent copy];
    newOAIInlineResponse2003.height = [obj.height copy];
}

@end
