#import <Foundation/Foundation.h>
#import "OAIInlineObject.h"
#import "OAIInlineResponse200.h"
#import "OAIInlineResponse2001.h"
#import "OAIInlineResponse2002.h"
#import "OAIInlineResponse2003.h"
#import "OAIInlineResponse2004.h"
#import "OAIInlineResponse2005.h"
#import "OAIInlineResponse2006.h"
#import "OAIInlineResponse2007.h"
#import "OAIInlineResponseDefault.h"
#import "OAIApi.h"

/**
* Skycoin REST API.
* Skycoin is a next-generation cryptocurrency.
*
* OpenAPI spec version: 0.25.1
* Contact: contact@skycoin.net
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/



@interface OAIDefaultApi: NSObject <OAIApi>

extern NSString* kOAIDefaultApiErrorDomain;
extern NSInteger kOAIDefaultApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(OAIApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Returns the total number of unique address that have coins.
/// 
///
/// 
///  code:200 message:"This endpoint Returns the total number of unique address that have coins.",
///  code:0 message:"A GenericError is the default error message that is generated. For certain status codes there are more appropriate error structures."
///
/// @return NSObject*
-(NSURLSessionTask*) addressCountWithCompletionHandler: 
    (void (^)(NSObject* output, NSError* error)) handler;


/// 
/// Returns the historical, spent outputs associated with an address
///
/// @param address address to filter by
/// 
///  code:200 message:"Response for endpoint /api/v1/address_uxouts",
///  code:0 message:"A GenericError is the default error message that is generated. For certain status codes there are more appropriate error structures."
///
/// @return NSArray<OAIInlineResponse200>*
-(NSURLSessionTask*) addressUxoutsWithAddress: (NSString*) address
    completionHandler: (void (^)(NSArray<OAIInlineResponse200>* output, NSError* error)) handler;


/// Returns the balance of one or more addresses, both confirmed and predicted. The predicted balance is the confirmed balance minus the pending spends.
/// 
///
/// @param addrs command separated list of addresses
/// 
///  code:200 message:"Returns the balance of one or more addresses",
///  code:0 message:"A GenericError is the default error message that is generated. For certain status codes there are more appropriate error structures."
///
/// @return NSObject*
-(NSURLSessionTask*) balanceGetWithAddrs: (NSString*) addrs
    completionHandler: (void (^)(NSObject* output, NSError* error)) handler;


/// Returns the balance of one or more addresses, both confirmed and predicted. The predicted balance is the confirmed balance minus the pending spends.
/// 
///
/// @param addrs command separated list of addresses
/// 
///  code:200 message:"Returns the balance of one or more addresses",
///  code:0 message:"A GenericError is the default error message that is generated. For certain status codes there are more appropriate error structures."
///
/// @return NSObject*
-(NSURLSessionTask*) balancePostWithAddrs: (NSString*) addrs
    completionHandler: (void (^)(NSObject* output, NSError* error)) handler;


/// 
/// Returns a block by hash or seq. Note: only one of hash or seq is allowed
///
/// @param hash  (optional)
/// @param seq  (optional)
/// 
///  code:200 message:"BlockVerbose represents a readable block with verbose data.",
///  code:0 message:"A GenericError is the default error message that is generated. For certain status codes there are more appropriate error structures."
///
/// @return NSObject*
-(NSURLSessionTask*) blockWithHash: (NSString*) hash
    seq: (NSNumber*) seq
    completionHandler: (void (^)(NSObject* output, NSError* error)) handler;


/// Returns the blockchain metadata.
/// 
///
/// 
///  code:200 message:"This endpoint returns the blockchain metadata.",
///  code:0 message:"A GenericError is the default error message that is generated. For certain status codes there are more appropriate error structures."
///
/// @return NSObject*
-(NSURLSessionTask*) blockchainMetadataWithCompletionHandler: 
    (void (^)(NSObject* output, NSError* error)) handler;


/// Returns the blockchain sync progress.
/// 
///
/// 
///  code:200 message:"This endpoint returns the blockchain sync progress",
///  code:0 message:"A GenericError is the default error message that is generated. For certain status codes there are more appropriate error structures."
///
/// @return NSObject*
-(NSURLSessionTask*) blockchainProgressWithCompletionHandler: 
    (void (^)(NSObject* output, NSError* error)) handler;


/// blocksHandler returns blocks between a start and end point,
/// or an explicit list of sequences. If using start and end, the block sequences include both the start and end point. Explicit sequences cannot be combined with start and end. Without verbose.
///
/// @param start  (optional)
/// @param end  (optional)
/// @param seqs  (optional)
/// 
///  code:200 message:"Returns blocks between a start and end point.",
///  code:0 message:"A GenericError is the default error message that is generated. For certain status codes there are more appropriate error structures."
///
/// @return NSObject*
-(NSURLSessionTask*) blocksGetWithStart: (NSNumber*) start
    end: (NSNumber*) end
    seqs: (NSArray<NSNumber*>*) seqs
    completionHandler: (void (^)(NSObject* output, NSError* error)) handler;


/// blocksHandler returns blocks between a start and end point,
/// or an explicit list of sequences. If using start and end, the block sequences include both the start and end point. Explicit sequences cannot be combined with start and end. Without verbose
///
/// @param start  (optional)
/// @param end  (optional)
/// @param seqs  (optional)
/// 
///  code:200 message:"Returns blocks between a start and end point.",
///  code:0 message:"A GenericError is the default error message that is generated. For certain status codes there are more appropriate error structures."
///
/// @return NSObject*
-(NSURLSessionTask*) blocksPostWithStart: (NSNumber*) start
    end: (NSNumber*) end
    seqs: (NSArray<NSNumber*>*) seqs
    completionHandler: (void (^)(NSObject* output, NSError* error)) handler;


/// 
/// coinSupplyHandler returns coin distribution supply stats
///
/// 
///  code:200 message:"CoinSupply records the coin supply info.",
///  code:0 message:"A GenericError is the default error message that is generated. For certain status codes there are more appropriate error structures."
///
/// @return void
-(NSURLSessionTask*) coinSupplyWithCompletionHandler: 
    (void (^)(NSError* error)) handler;


/// Creates a new CSRF token. Previous CSRF tokens are invalidated by this call.
/// 
///
/// 
///  code:200 message:"Return a csrf Token.",
///  code:0 message:"A GenericError is the default error message that is generated. For certain status codes there are more appropriate error structures."
///
/// @return OAIInlineResponse2001*
-(NSURLSessionTask*) csrfWithCompletionHandler: 
    (void (^)(OAIInlineResponse2001* output, NSError* error)) handler;


/// defaultConnectionsHandler returns the list of default hardcoded bootstrap addresses.\\n They are not necessarily connected to.
/// 
///
/// 
///  code:200 message:"This endpoint return an list of default connections.",
///  code:0 message:"A GenericError is the default error message that is generated. For certain status codes there are more appropriate error structures."
///
/// @return NSArray<NSString*>*
-(NSURLSessionTask*) defaultConnectionsWithCompletionHandler: 
    (void (^)(NSArray<NSString*>* output, NSError* error)) handler;


/// 
/// Returns all transactions (confirmed and unconfirmed) for an address
///
/// @param address tags to filter by (optional)
/// 
///  code:200 message:"Response for endpoint /api/v1/explorer/address",
///  code:0 message:"A GenericError is the default error message that is generated. For certain status codes there are more appropriate error structures."
///
/// @return NSArray<OAIInlineResponse2002>*
-(NSURLSessionTask*) explorerAddressWithAddress: (NSString*) address
    completionHandler: (void (^)(NSArray<OAIInlineResponse2002>* output, NSError* error)) handler;


/// Returns node health data.
/// 
///
/// 
///  code:200 message:"This endpoint returns node health data.",
///  code:0 message:"A GenericError is the default error message that is generated. For certain status codes there are more appropriate error structures."
///
/// @return NSObject*
-(NSURLSessionTask*) healthWithCompletionHandler: 
    (void (^)(NSObject* output, NSError* error)) handler;


/// 
/// Returns the most recent N blocks on the blockchain
///
/// @param num 
/// 
///  code:200 message:"Returns the most recent N blocks on the blockchain.",
///  code:0 message:"A GenericError is the default error message that is generated. For certain status codes there are more appropriate error structures."
///
/// @return NSObject*
-(NSURLSessionTask*) lastBlocksWithNum: (NSNumber*) num
    completionHandler: (void (^)(NSObject* output, NSError* error)) handler;


/// This endpoint returns a specific connection.
/// 
///
/// @param addr Address port
/// 
///  code:200 message:"This endpoint return a connection struct",
///  code:0 message:"A GenericError is the default error message that is generated. For certain status codes there are more appropriate error structures."
///
/// @return OAIInlineResponse2003*
-(NSURLSessionTask*) networkConnectionWithAddr: (NSString*) addr
    completionHandler: (void (^)(OAIInlineResponse2003* output, NSError* error)) handler;


/// This endpoint returns all outgoings connections.
/// 
///
/// @param states Connection status. (optional)
/// @param direction Direction of the connection. (optional)
/// 
///  code:200 message:"This endpoint return a connection struct",
///  code:0 message:"A GenericError is the default error message that is generated. For certain status codes there are more appropriate error structures."
///
/// @return NSArray<OAIInlineResponse2003>*
-(NSURLSessionTask*) networkConnectionsWithStates: (NSString*) states
    direction: (NSString*) direction
    completionHandler: (void (^)(NSArray<OAIInlineResponse2003>* output, NSError* error)) handler;


/// 
/// This endpoint disconnects a connection by ID or address
///
/// @param _id Address id.
/// 
///  code:200 message:"This endpoint",
///  code:0 message:"A GenericError is the default error message that is generated. For certain status codes there are more appropriate error structures."
///
/// @return void
-(NSURLSessionTask*) networkConnectionsDisconnectWithId: (NSString*) _id
    completionHandler: (void (^)(NSError* error)) handler;


/// 
/// This endpoint returns all connections found through peer exchange
///
/// 
///  code:200 message:"This endpoint return a list of all connections found through peer exchange.",
///  code:0 message:"A GenericError is the default error message that is generated. For certain status codes there are more appropriate error structures."
///
/// @return NSArray<NSString*>*
-(NSURLSessionTask*) networkConnectionsExchangeWithCompletionHandler: 
    (void (^)(NSArray<NSString*>* output, NSError* error)) handler;


/// trustConnectionsHandler returns all trusted connections.\\n They are not necessarily connected to. In the default configuration, these will be a subset of the default hardcoded bootstrap addresses.
/// 
///
/// 
///  code:200 message:"This endpoint return a list of trusted connections.",
///  code:0 message:"A GenericError is the default error message that is generated. For certain status codes there are more appropriate error structures."
///
/// @return NSArray<NSString*>*
-(NSURLSessionTask*) networkConnectionsTrustWithCompletionHandler: 
    (void (^)(NSArray<NSString*>* output, NSError* error)) handler;


/// If neither addrs nor hashes are specificed, return all unspent outputs. If only one filter is specified, then return outputs match the filter. Both filters cannot be specified.
/// 
///
/// @param address  (optional)
/// @param hash  (optional)
/// 
///  code:200 message:"UnspentOutputsSummary records unspent outputs in different status.",
///  code:0 message:"A GenericError is the default error message that is generated. For certain status codes there are more appropriate error structures."
///
/// @return NSObject*
-(NSURLSessionTask*) outputsGetWithAddress: (NSArray<NSString*>*) address
    hash: (NSArray<NSString*>*) hash
    completionHandler: (void (^)(NSObject* output, NSError* error)) handler;


/// If neither addrs nor hashes are specificed, return all unspent outputs. If only one filter is specified, then return outputs match the filter. Both filters cannot be specified.
/// 
///
/// @param address  (optional)
/// @param hash  (optional)
/// 
///  code:200 message:"UnspentOutputsSummary records unspent outputs in different status.",
///  code:0 message:"A GenericError is the default error message that is generated. For certain status codes there are more appropriate error structures."
///
/// @return NSObject*
-(NSURLSessionTask*) outputsPostWithAddress: (NSString*) address
    hash: (NSString*) hash
    completionHandler: (void (^)(NSObject* output, NSError* error)) handler;


/// 
/// Returns pending (unconfirmed) transactions without verbose
///
/// 
///  code:200 message:"Returns a transaction identified by its txid hash.",
///  code:0 message:"A GenericError is the default error message that is generated. For certain status codes there are more appropriate error structures."
///
/// @return NSArray<OAIInlineResponse2004>*
-(NSURLSessionTask*) pendingTxsWithCompletionHandler: 
    (void (^)(NSArray<OAIInlineResponse2004>* output, NSError* error)) handler;


/// 
/// Broadcasts all unconfirmed transactions from the unconfirmed transaction pool
///
/// 
///  code:200 message:"OK, Broadcasts all unconfirmed transactions from the unconfirmed transaction pool",
///  code:0 message:"A GenericError is the default error message that is generated. For certain status codes there are more appropriate error structures."
///
/// @return void
-(NSURLSessionTask*) resendUnconfirmedTxnsWithCompletionHandler: 
    (void (^)(NSError* error)) handler;


/// Returns the top skycoin holders.
/// 
///
/// @param includeDistribution include distribution addresses or not, default value false (optional)
/// @param n include distribution addresses or not, default value false (optional)
/// 
///  code:200 message:"Response for endpoint /api/v1/address_uxouts",
///  code:0 message:"A GenericError is the default error message that is generated. For certain status codes there are more appropriate error structures."
///
/// @return NSObject*
-(NSURLSessionTask*) richlistWithIncludeDistribution: (NSNumber*) includeDistribution
    n: (NSString*) n
    completionHandler: (void (^)(NSObject* output, NSError* error)) handler;


/// 
/// Returns a transaction identified by its txid hash with just id
///
/// @param txid transaction hash
/// @param encoded return as a raw encoded transaction. (optional)
/// 
///  code:200 message:"Returns a transaction identified by its txid hash.",
///  code:0 message:"A GenericError is the default error message that is generated. For certain status codes there are more appropriate error structures."
///
/// @return NSObject*
-(NSURLSessionTask*) transactionWithTxid: (NSString*) txid
    encoded: (NSNumber*) encoded
    completionHandler: (void (^)(NSObject* output, NSError* error)) handler;


/// Broadcast a hex-encoded, serialized transaction to the network.
/// 
///
/// @param rawtx hex-encoded serialized transaction string.
/// 
///  code:200 message:"Ok, returns the transaction.",
///  code:0 message:"A GenericError is the default error message that is generated. For certain status codes there are more appropriate error structures."
///
/// @return NSObject*
-(NSURLSessionTask*) transactionInjectWithRawtx: (NSString*) rawtx
    completionHandler: (void (^)(NSObject* output, NSError* error)) handler;


/// Returns the hex-encoded byte serialization of a transaction. The transaction may be confirmed or unconfirmed.
/// 
///
/// @param txid Transaction id hash (optional)
/// 
///  code:200 message:"Returns the hex-encoded byte serialization of a transaction",
///  code:0 message:"A GenericError is the default error message that is generated. For certain status codes there are more appropriate error structures."
///
/// @return NSObject*
-(NSURLSessionTask*) transactionRawWithTxid: (NSString*) txid
    completionHandler: (void (^)(NSObject* output, NSError* error)) handler;


/// 
/// Decode and verify an encoded transaction
///
/// 
///  code:200 message:"Responses ok",
///  code:0 message:"A GenericError is the default error message that is generated. For certain status codes there are more appropriate error structures."
///
/// @return NSObject*
-(NSURLSessionTask*) transactionVerifyWithCompletionHandler: 
    (void (^)(NSObject* output, NSError* error)) handler;


/// Returns transactions that match the filters.
/// 
///
/// @param addrs command separated list of addresses (optional)
/// @param confirmed Whether the transactions should be confirmed [optional, must be 0 or 1; if not provided, returns all] (optional)
/// 
///  code:200 message:"Returns transactions that match the filters.",
///  code:0 message:"A GenericError is the default error message that is generated. For certain status codes there are more appropriate error structures."
///
/// @return NSObject*
-(NSURLSessionTask*) transactionsGetWithAddrs: (NSString*) addrs
    confirmed: (NSString*) confirmed
    completionHandler: (void (^)(NSObject* output, NSError* error)) handler;


/// Returns transactions that match the filters.
/// 
///
/// @param addrs command separated list of addresses (optional)
/// @param confirmed Whether the transactions should be confirmed [optional, must be 0 or 1; if not provided, returns all] (optional)
/// 
///  code:200 message:"Returns transactions that match the filters.",
///  code:0 message:"A GenericError is the default error message that is generated. For certain status codes there are more appropriate error structures."
///
/// @return NSObject*
-(NSURLSessionTask*) transactionsPostWithAddrs: (NSString*) addrs
    confirmed: (NSString*) confirmed
    completionHandler: (void (^)(NSObject* output, NSError* error)) handler;


/// Returns an unspent output by ID.
/// 
///
/// @param uxid uxid to filter by (optional)
/// 
///  code:200 message:"Response for endpoint /api/v1/uxout",
///  code:0 message:"A GenericError is the default error message that is generated. For certain status codes there are more appropriate error structures."
///
/// @return NSObject*
-(NSURLSessionTask*) uxoutWithUxid: (NSString*) uxid
    completionHandler: (void (^)(NSObject* output, NSError* error)) handler;


/// Verifies a Skycoin address.
/// 
///
/// @param address Address id.
/// 
///  code:200 message:"Response verifies a Skycoin address",
///  code:0 message:"A GenericError is the default error message that is generated. For certain status codes there are more appropriate error structures."
///
/// @return OAIInlineResponse2007*
-(NSURLSessionTask*) verifyAddressWithAddress: (NSString*) address
    completionHandler: (void (^)(OAIInlineResponse2007* output, NSError* error)) handler;


/// 
/// versionHandler returns the application version info
///
/// 
///  code:200 message:"BuildInfo represents the build info",
///  code:0 message:"A GenericError is the default error message that is generated. For certain status codes there are more appropriate error structures."
///
/// @return void
-(NSURLSessionTask*) versionWithCompletionHandler: 
    (void (^)(NSError* error)) handler;


/// Returns a wallet by id.
/// 
///
/// @param _id tags to filter by
/// 
///  code:200 message:"Response for endpoint /api/v1/wallet",
///  code:0 message:"A GenericError is the default error message that is generated. For certain status codes there are more appropriate error structures."
///
/// @return NSObject*
-(NSURLSessionTask*) walletWithId: (NSString*) _id
    completionHandler: (void (^)(NSObject* output, NSError* error)) handler;


/// Returns the wallet's balance, both confirmed and predicted.  The predicted balance is the confirmed balance minus the pending spends.
/// 
///
/// @param _id tags to filter by
/// 
///  code:200 message:"Returns the wallets balance",
///  code:0 message:"A GenericError is the default error message that is generated. For certain status codes there are more appropriate error structures."
///
/// @return NSObject*
-(NSURLSessionTask*) walletBalanceWithId: (NSString*) _id
    completionHandler: (void (^)(NSObject* output, NSError* error)) handler;


/// 
/// Loads wallet from seed, will scan ahead N address and load addresses till the last one that have coins.
///
/// @param seed Wallet seed.
/// @param label Wallet label.
/// @param scan The number of addresses to scan ahead for balances. (optional)
/// @param encrypt Encrypt wallet. (optional)
/// @param password Wallet Password (optional)
/// 
///  code:200 message:"This endpoint loads wallets from seed",
///  code:0 message:"A GenericError is the default error message that is generated. For certain status codes there are more appropriate error structures."
///
/// @return NSObject*
-(NSURLSessionTask*) walletCreateWithSeed: (NSString*) seed
    label: (NSString*) label
    scan: (NSNumber*) scan
    encrypt: (NSNumber*) encrypt
    password: (NSString*) password
    completionHandler: (void (^)(NSObject* output, NSError* error)) handler;


/// Decrypts wallet.
/// 
///
/// @param _id Wallet id.
/// @param password Wallet password.
/// 
///  code:200 message:"This endpoint decrypts wallets.",
///  code:0 message:"A GenericError is the default error message that is generated. For certain status codes there are more appropriate error structures."
///
/// @return NSObject*
-(NSURLSessionTask*) walletDecryptWithId: (NSString*) _id
    password: (NSString*) password
    completionHandler: (void (^)(NSObject* output, NSError* error)) handler;


/// Encrypt wallet.
/// 
///
/// @param _id Wallet id.
/// @param password Wallet password.
/// 
///  code:200 message:"This endpoint encrypt wallets.",
///  code:0 message:"A GenericError is the default error message that is generated. For certain status codes there are more appropriate error structures."
///
/// @return NSObject*
-(NSURLSessionTask*) walletEncryptWithId: (NSString*) _id
    password: (NSString*) password
    completionHandler: (void (^)(NSObject* output, NSError* error)) handler;


/// 
/// Returns the wallet directory path
///
/// @param addr Address port
/// 
///  code:200 message:"This endpoint return the wallet directory path",
///  code:0 message:"A GenericError is the default error message that is generated. For certain status codes there are more appropriate error structures."
///
/// @return OAIInlineResponse2006*
-(NSURLSessionTask*) walletFolderWithAddr: (NSString*) addr
    completionHandler: (void (^)(OAIInlineResponse2006* output, NSError* error)) handler;


/// 
/// Generates new addresses
///
/// @param _id Wallet Id
/// @param num The number you want to generate (optional)
/// @param password Wallet Password (optional)
/// 
///  code:200 message:"This endpoint generate new addresses",
///  code:0 message:"A GenericError is the default error message that is generated. For certain status codes there are more appropriate error structures."
///
/// @return NSObject*
-(NSURLSessionTask*) walletNewAddressWithId: (NSString*) _id
    num: (NSString*) num
    password: (NSString*) password
    completionHandler: (void (^)(NSObject* output, NSError* error)) handler;


/// 
/// Returns the wallet directory path
///
/// @param entropy Entropy bitSize. (optional)
/// 
///  code:200 message:"Generates wallet seed",
///  code:0 message:"A GenericError is the default error message that is generated. For certain status codes there are more appropriate error structures."
///
/// @return NSObject*
-(NSURLSessionTask*) walletNewSeedWithEntropy: (NSString*) entropy
    completionHandler: (void (^)(NSObject* output, NSError* error)) handler;


/// Recovers an encrypted wallet by providing the seed. The first address will be generated from seed and compared to the first address of the specified wallet. If they match, the wallet will be regenerated with an optional password. If the wallet is not encrypted, an error is returned.
/// 
///
/// @param _id Wallet id.
/// @param seed Wallet seed.
/// @param password Wallet password. (optional)
/// 
///  code:200 message:"This endpoint decrypts wallets.",
///  code:0 message:"A GenericError is the default error message that is generated. For certain status codes there are more appropriate error structures."
///
/// @return NSObject*
-(NSURLSessionTask*) walletRecoverWithId: (NSString*) _id
    seed: (NSString*) seed
    password: (NSString*) password
    completionHandler: (void (^)(NSObject* output, NSError* error)) handler;


/// This endpoint only works for encrypted wallets. If the wallet is unencrypted, The seed will be not returned.
/// 
///
/// @param _id Wallet Id.
/// @param password Wallet password.
/// 
///  code:200 message:"This endpoint Returns seed of wallet of given id",
///  code:0 message:"A GenericError is the default error message that is generated. For certain status codes there are more appropriate error structures."
///
/// @return NSObject*
-(NSURLSessionTask*) walletSeedWithId: (NSString*) _id
    password: (NSString*) password
    completionHandler: (void (^)(NSObject* output, NSError* error)) handler;


/// Verifies a wallet seed.
/// 
///
/// @param seed Seed to be verified. (optional)
/// 
///  code:200 message:"Verifies a wallet seed.",
///  code:422 message:"Wrong Seed",
///  code:0 message:"A GenericError is the default error message that is generated. For certain status codes there are more appropriate error structures."
///
/// @return NSObject*
-(NSURLSessionTask*) walletSeedVerifyWithSeed: (NSString*) seed
    completionHandler: (void (^)(NSObject* output, NSError* error)) handler;


/// 
/// Creates and broadcasts a transaction sending money from one of our wallets to destination address.
///
/// @param _id Wallet id
/// @param dst Recipient address
/// @param coins Number of coins to spend, in droplets. 1 coin equals 1e6 droplets.
/// @param password Wallet password.
/// 
///  code:200 message:"Creates and broadcasts a transaction sending money from one of our wallets to destination address.",
///  code:0 message:"A GenericError is the default error message that is generated. For certain status codes there are more appropriate error structures."
///
/// @return NSObject*
-(NSURLSessionTask*) walletSpentWithId: (NSString*) _id
    dst: (NSString*) dst
    coins: (NSString*) coins
    password: (NSString*) password
    completionHandler: (void (^)(NSObject* output, NSError* error)) handler;


/// 
/// Creates a signed transaction
///
/// @param inlineObject  (optional)
/// 
///  code:200 message:"Returns blocks between a start and end point.",
///  code:0 message:"A GenericError is the default error message that is generated. For certain status codes there are more appropriate error structures."
///
/// @return NSObject*
-(NSURLSessionTask*) walletTransactionWithInlineObject: (OAIInlineObject*) inlineObject
    completionHandler: (void (^)(NSObject* output, NSError* error)) handler;


/// 
/// Returns returns all unconfirmed transactions for all addresses in a given wallet verbose
///
/// @param _id Wallet id.
/// 
///  code:200 message:"Returns returns all unconfirmed transactions for all addresses in a given wallet",
///  code:0 message:"A GenericError is the default error message that is generated. For certain status codes there are more appropriate error structures."
///
/// @return NSObject*
-(NSURLSessionTask*) walletTransactionsWithId: (NSString*) _id
    completionHandler: (void (^)(NSObject* output, NSError* error)) handler;


/// Unloads wallet from the wallet service.
/// 
///
/// @param _id Wallet Id.
/// 
///  code:200 message:"This endpoint returns nothing.",
///  code:0 message:"A GenericError is the default error message that is generated. For certain status codes there are more appropriate error structures."
///
/// @return void
-(NSURLSessionTask*) walletUnloadWithId: (NSString*) _id
    completionHandler: (void (^)(NSError* error)) handler;


/// Update the wallet.
/// 
///
/// @param _id Wallet Id.
/// @param label The label the wallet will be updated to.
/// 
///  code:200 message:"This endpoint Returns the label the wallet will be updated to .",
///  code:0 message:"A GenericError is the default error message that is generated. For certain status codes there are more appropriate error structures."
///
/// @return void
-(NSURLSessionTask*) walletUpdateWithId: (NSString*) _id
    label: (NSString*) label
    completionHandler: (void (^)(NSError* error)) handler;


/// 
/// Returns all loaded wallets
///
/// 
///  code:200 message:"This endpoint return all loaded wallets",
///  code:0 message:"A GenericError is the default error message that is generated. For certain status codes there are more appropriate error structures."
///
/// @return NSArray<OAIInlineResponse2005>*
-(NSURLSessionTask*) walletsWithCompletionHandler: 
    (void (^)(NSArray<OAIInlineResponse2005>* output, NSError* error)) handler;



@end
